# Assignment - PY/02
- Lambda Functions

In [3]:
import pandas as pd
from pydataset import data
from functools import reduce
# Load mtcars dataset
df = data('mtcars')

In [4]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

### 4.1 Add Two Columns
- Create a new column mpg_hp_sum = mpg + hp using a lambda function.

In [8]:
df['mpg_hp_sum'] = df. apply (lambda r: r['mpg'] + r['hp'], axis=1)

In [10]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low

### 4.2 Conditional Label
- Create a new column mpg_label:
	•	"High" if mpg > 20
	•	"Low" otherwise
- Use apply() with a lambda.

In [7]:
df['mpg_label'] = df["mpg"].apply (lambda r: 'High' if r > 20 else 'Low')  
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low

### 4.3 Multiply Column Values
- Double all hp values using map() with a lambda.

In [ ]:
df['hp'] = df['hp'].map(lambda x: x * 2)
df.head()

In [ ]:
## df['hp'] = df['hp'].apply(lambda x: x * 2)
#df.head()

In [ ]:
#df.map(lambda x: x * 2)

### 4.4 Filter Rows
- Get a list of all mpg values greater than 25 using filter() with a lambda.

In [ ]:
 list(filter(lambda x: x > 25, df['mpg']))

### 4.5 Reduce to Total
- Use reduce() with a lambda to sum all cyl values in the dataset.

In [11]:
reduce (lambda x, y: x + y, df['cyl'])

198

### 4.6 Sort by Custom Rule
- Sort the dataset by the reverse of the car names’ length using sorted() with a lambda on the index.

In [ ]:
df.loc[sorted(df.index, key= lambda x: len(x), reverse =True)]

### 4.7 Multi-Column Condition
- Create a column efficient_power = "Yes" if mpg > 20 and hp > 100, else "No".|

In [ ]:
df['efficient_power'] = df.apply(lambda row: 'Yes' if row['mpg'] > 20 and row['hp'] > 100 else 'No', axis=1)
df.head()

### 4.8 Normalize a Column
- Normalize mpg between 0 and 1 using a lambda inside apply():
- {normalized} = (x - min)/(max - min)

In [ ]:
min_mpg = df['mpg'].min()
max_mpg = df['mpg'].max()

df['mpg_normalized'] = df['mpg'].apply(lambda x: (x - min_mpg) / (max_mpg - min_mpg))
df.head()

### 4.9 Extract First Word
- Extract the first word from each car name (index) into a new column car_make using map() with a lambda.

In [ ]:
df['car_make'] = df.index.map(lambda x: x.split()[0])
df.head()

### 4.10 Square and Add
- Create a column hp_mpg_calc = (hp² + mpg²) using apply() with a lambda.

In [ ]:
df['hp_mpg_calc'] = df.apply(lambda row: (row['hp']*2) + (row['mpg']*2), axis=1)
df.head()

### 4.11 Filter by Col values
- Filter cars with mpg > 25.

In [ ]:
df_filtered = df[df['mpg'] > 25]
df_filtered

### 4.12 Filter and soted carnames by horsepower
- From above return a list of car names sorted by horsepower.

In [ ]:
list(df_filtered.sort_values(by='hp').index)

# End Here
- docs - 1nWPAH4oD_DNP9lfJXtrlrgufld4YwYoJHVoNUtWZGS4