# Assignment - PY/02
- Lambda Functions

In [1]:
import pandas as pd
from pydataset import data
from functools import reduce
# Load mtcars dataset
df = data('mtcars')

In [2]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

### 4.1 Add Two Columns
- Create a new column mpg_hp_sum = mpg + hp using a lambda function.

In [3]:
df['mpg_hp_sum'] = df. apply (lambda r: r['mpg'] + r['hp'], axis=1)

In [4]:
df['mpg_hp_sum']

Mazda RX4              131.0
Mazda RX4 Wag          131.0
Datsun 710             115.8
Hornet 4 Drive         131.4
Hornet Sportabout      193.7
Valiant                123.1
Duster 360             259.3
Merc 240D               86.4
Merc 230               117.8
Merc 280               142.2
Merc 280C              140.8
Merc 450SE             196.4
Merc 450SL             197.3
Merc 450SLC            195.2
Cadillac Fleetwood     215.4
Lincoln Continental    225.4
Chrysler Imperial      244.7
Fiat 128                98.4
Honda Civic             82.4
Toyota Corolla          98.9
Toyota Corona          118.5
Dodge Challenger       165.5
AMC Javelin            165.2
Camaro Z28             258.3
Pontiac Firebird       194.2
Fiat X1-9               93.3
Porsche 914-2          117.0
Lotus Europa           143.4
Ford Pantera L         279.8
Ferrari Dino           194.7
Maserati Bora          350.0
Volvo 142E             130.4
Name: mpg_hp_sum, dtype: float64

### 4.2 Conditional Label
- Create a new column mpg_label:
	•	"High" if mpg > 20
	•	"Low" otherwise
- Use apply() with a lambda.

In [5]:
df['mpg_label'] = df["mpg"].apply (lambda r: 'High' if r > 20 else 'Low')  
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low

### 4.3 Multiply Column Values
- Double all hp values using map() with a lambda.

In [6]:
df['hp'] = df['hp'].map(lambda x: x * 2)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label
Mazda RX4,21.0,6,160.0,220,3.90,2.620,16.46,0,1,4,4,131.0,High
Mazda RX4 Wag,21.0,6,160.0,220,3.90,2.875,17.02,0,1,4,4,131.0,High
Datsun 710,22.8,4,108.0,186,3.85,2.320,18.61,1,1,4,1,115.8,High
Hornet 4 Drive,21.4,6,258.0,220,3.08,3.215,19.44,1,0,3,1,131.4,High
Hornet Sportabout,18.7,8,360.0,350,3.15,3.440,17.02,0,0,3,2,193.7,Low

In [7]:
## df['hp'] = df['hp'].apply(lambda x: x * 2)
#df.head()

In [8]:
#df.map(lambda x: x * 2)

### 4.4 Filter Rows
- Get a list of all mpg values greater than 25 using filter() with a lambda.

In [6]:
 list(filter(lambda x: x > 25, df['mpg']))

[32.4, 30.4, 33.9, 27.3, 26.0, 30.4]

### 4.5 Reduce to Total
- Use reduce() with a lambda to sum all cyl values in the dataset.

In [7]:
reduce (lambda x, y: x + y, df['cyl'])

198

### 4.6 Sort by Custom Rule
- Sort the dataset by the reverse of the car names’ length using sorted() with a lambda on the index.

In [9]:
df.loc[sorted(df.index, key= lambda x: len(x), reverse =True)]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label
Lincoln Continental,10.4,8,460.0,430,3.00,5.424,17.82,0,0,3,4,225.4,Low
Cadillac Fleetwood,10.4,8,472.0,410,2.93,5.250,17.98,0,0,3,4,215.4,Low
Hornet Sportabout,18.7,8,360.0,350,3.15,3.440,17.02,0,0,3,2,193.7,Low
Chrysler Imperial,14.7,8,440.0,460,3.23,5.345,17.42,0,0,3,4,244.7,Low
Dodge Challenger,15.5,8,318.0,300,2.76,3.520,16.87,0,0,3,2,165.5,Low
Pontiac Firebird,19.2,8,400.0,350,3.08,3.845,17.05,0,0,3,2,194.2,Low
Hornet 4 Drive,21.4,6,258.0,220,3.08,3.215,19.44,1,0,3,1,131.4,High
Toyota Corolla,33.9,4,71.1,130,4.22,1.835,19.90,1,1,4,1,98.9,High
Ford Pantera L,15.8,8,351.0,528,4.22,3.170,14.50,0,1,5,4,279.8,Low
Mazda RX4 Wag,21.0,6,160.0,220,3.90,2.875,17.02,0,1,4,4,131.0,High
Toyota Corona,21.5,4,120.1,194,3.70,2.465,20.01,1,0,3,1,118.5,High
Porsche 914-2,26.0,4,120.3,182,4.43,2.140,16.70,0,1,5,2,117.0,High
Maserati Bora,15.0,8,301.0,670,3.54,3.570,14.60,0,1,5,8,350.0,Low
Lotus Europa,30.4,4,95.1,226,3.77,1.513,16.90,1,1,5,2,143.4,High
Ferrari Dino,19.7,6,145.0,350,3.62,2.770,15.50,0,1,5,6,194.7,Low
Merc 450SLC,15.2,8,275.8,360,3.07,3.780,18.00,0,0,3,3,195.2,Low
Honda Civic,30.4,4,75.7,104,4.93,1.615,18.52,1,1,4,2,82.4,High
AMC Javelin,15.2,8,304.0,300,3.15,3.435,17.30,0,0,3,2,165.2,Low
Datsun 710,22.8,4,108.0,186,3.85,2.320,18.61,1,1,4,1,115.8,High
Duster 360,14.3,8,360.0,490,3.21,3.570,15.84,0,0,3,4,259.3,Low
Merc 450SE,16.4,8,275.8,360,3.07,4.070,17.40,0,0,3,3,196.4,Low
Merc 450SL,17.3,8,275.8,360,3.07,3.730,17.60,0,0,3,3,197.3,Low
Camaro Z28,13.3,8,350.0,490,3.73,3.840,15.41,0,0,3,4,258.3,Low
Volvo 142E,21.4,4,121.0,218,4.11,2.780,18.60,1,1,4,2,130.4,High
Mazda RX4,21.0,6,160.0,220,3.90,2.620,16.46,0,1,4,4,131.0,High
Merc 240D,24.4,4,146.7,124,3.69,3.190,20.00,1,0,4,2,86.4,High
Merc 280C,17.8,6,167.6,246,3.92,3.440,18.90,1,0,4,4,140.8,Low
Fiat X1-9,27.3,4,79.0,132,4.08,1.935,18.90,1,1,4,1,93.3,High
Merc 230,22.8,4,140.8,190,3.92,3.150,22.90,1,0,4,2,117.8,High
Merc 280,19.2,6,167.6,246,3.92,3.440,18.30,1,0,4,4,142.2,Low
Fiat 128,32.4,4,78.7,132,4.08,2.200,19.47,1,1,4,1,98.4,High
Valiant,18.1,6,225.0,210,2.76,3.460,20.22,1,0,3,1,123.1,Low

### 4.7 Multi-Column Condition
- Create a column efficient_power = "Yes" if mpg > 20 and hp > 100, else "No".|

In [10]:
df['efficient_power'] = df.apply(lambda row: 'Yes' if row['mpg'] > 20 and row['hp'] > 100 else 'No', axis=1)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,efficient_power
Mazda RX4,21.0,6,160.0,220,3.90,2.620,16.46,0,1,4,4,131.0,High,Yes
Mazda RX4 Wag,21.0,6,160.0,220,3.90,2.875,17.02,0,1,4,4,131.0,High,Yes
Datsun 710,22.8,4,108.0,186,3.85,2.320,18.61,1,1,4,1,115.8,High,Yes
Hornet 4 Drive,21.4,6,258.0,220,3.08,3.215,19.44,1,0,3,1,131.4,High,Yes
Hornet Sportabout,18.7,8,360.0,350,3.15,3.440,17.02,0,0,3,2,193.7,Low,No

### 4.8 Normalize a Column
- Normalize mpg between 0 and 1 using a lambda inside apply():
- {normalized} = (x - min)/(max - min)

In [12]:
min_mpg = df['mpg'].min()
max_mpg = df['mpg'].max()

df['mpg_normalized'] = df['mpg'].apply(lambda x: (x - min_mpg) / (max_mpg - min_mpg))
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,efficient_power,mpg_normalized
Mazda RX4,21.0,6,160.0,220,3.90,2.620,16.46,0,1,4,4,131.0,High,Yes,0.451064
Mazda RX4 Wag,21.0,6,160.0,220,3.90,2.875,17.02,0,1,4,4,131.0,High,Yes,0.451064
Datsun 710,22.8,4,108.0,186,3.85,2.320,18.61,1,1,4,1,115.8,High,Yes,0.527660
Hornet 4 Drive,21.4,6,258.0,220,3.08,3.215,19.44,1,0,3,1,131.4,High,Yes,0.468085
Hornet Sportabout,18.7,8,360.0,350,3.15,3.440,17.02,0,0,3,2,193.7,Low,No,0.353191

### 4.9 Extract First Word
- Extract the first word from each car name (index) into a new column car_make using map() with a lambda.

In [13]:
df['car_make'] = df.index.map(lambda x: x.split()[0])
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,efficient_power,mpg_normalized,car_make
Mazda RX4,21.0,6,160.0,220,3.90,2.620,16.46,0,1,4,4,131.0,High,Yes,0.451064,Mazda
Mazda RX4 Wag,21.0,6,160.0,220,3.90,2.875,17.02,0,1,4,4,131.0,High,Yes,0.451064,Mazda
Datsun 710,22.8,4,108.0,186,3.85,2.320,18.61,1,1,4,1,115.8,High,Yes,0.527660,Datsun
Hornet 4 Drive,21.4,6,258.0,220,3.08,3.215,19.44,1,0,3,1,131.4,High,Yes,0.468085,Hornet
Hornet Sportabout,18.7,8,360.0,350,3.15,3.440,17.02,0,0,3,2,193.7,Low,No,0.353191,Hornet

### 4.10 Square and Add
- Create a column hp_mpg_calc = (hp² + mpg²) using apply() with a lambda.

In [14]:
df['hp_mpg_calc'] = df.apply(lambda row: (row['hp']*2) + (row['mpg']*2), axis=1)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,efficient_power,mpg_normalized,car_make,hp_mpg_calc
Mazda RX4,21.0,6,160.0,220,3.90,2.620,16.46,0,1,4,4,131.0,High,Yes,0.451064,Mazda,482.0
Mazda RX4 Wag,21.0,6,160.0,220,3.90,2.875,17.02,0,1,4,4,131.0,High,Yes,0.451064,Mazda,482.0
Datsun 710,22.8,4,108.0,186,3.85,2.320,18.61,1,1,4,1,115.8,High,Yes,0.527660,Datsun,417.6
Hornet 4 Drive,21.4,6,258.0,220,3.08,3.215,19.44,1,0,3,1,131.4,High,Yes,0.468085,Hornet,482.8
Hornet Sportabout,18.7,8,360.0,350,3.15,3.440,17.02,0,0,3,2,193.7,Low,No,0.353191,Hornet,737.4

### 4.11 Filter by Col values
- Filter cars with mpg > 25.

In [15]:
df_filtered = df[df['mpg'] > 25]
df_filtered

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,efficient_power,mpg_normalized,car_make,hp_mpg_calc
Fiat 128,32.4,4,78.7,132,4.08,2.200,19.47,1,1,4,1,98.4,High,Yes,0.936170,Fiat,328.8
Honda Civic,30.4,4,75.7,104,4.93,1.615,18.52,1,1,4,2,82.4,High,Yes,0.851064,Honda,268.8
Toyota Corolla,33.9,4,71.1,130,4.22,1.835,19.90,1,1,4,1,98.9,High,Yes,1.000000,Toyota,327.8
Fiat X1-9,27.3,4,79.0,132,4.08,1.935,18.90,1,1,4,1,93.3,High,Yes,0.719149,Fiat,318.6
Porsche 914-2,26.0,4,120.3,182,4.43,2.140,16.70,0,1,5,2,117.0,High,Yes,0.663830,Porsche,416.0
Lotus Europa,30.4,4,95.1,226,3.77,1.513,16.90,1,1,5,2,143.4,High,Yes,0.851064,Lotus,512.8

### 4.12 Filter and soted carnames by horsepower
- From above return a list of car names sorted by horsepower.

In [16]:
list(df_filtered.sort_values(by='hp').index)

['Honda Civic',
 'Toyota Corolla',
 'Fiat 128',
 'Fiat X1-9',
 'Porsche 914-2',
 'Lotus Europa']

# End Here
- docs - 1nWPAH4oD_DNP9lfJXtrlrgufld4YwYoJHVoNUtWZGS4