1.Write the queries for the following
2.List the names of analysts and salesmen.
3.List details of employees who have joined before 30 Sep 81.
4.List names of employees who are not managers.
5.List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.
6.List employees not belonging to department 30, 40, or 10.
7.List employee names for those who have joined between 30 June and 31 Dec. ‘81.
8.List the different designations in the company.
9.List the names of employees who are not eligible for commission.
10.List the name and designation of the employee who does not report to anybody.
11.List the employees not assigned to any department.
12.List the employees who are eligible for commission.
13.List employees whose names either start or end with “S”.
14.List names of employees whose names have “i” as the second character.
15.List the number of employees working with the company.
16.List the number of designations available in the EMP table.
17.List the total salaries paid to the employees.
18.List the maximum, minimum and average salary in the company.
19.List the maximum salary paid to a salesman.

In [1]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd 
import os

In [2]:
engine1 = create_engine("mysql+pymysql://root:piit2025@localhost:3306/piit")

In [3]:
def q(sql, **params):
 with engine1.connect() as conn:
  return pd.read_sql(text(sql), conn, params=params)

In [4]:
q("show tables")

  Tables_in_piit
0         aelita
1           dept
2            emp
3       students

In [5]:
emp= q("SELECT * FROM emp")
emp

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    1324    SHAN    ANALYST  7839.0  1988-12-17  4000.0    50.0      10
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
3    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
4    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
6    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
7    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
8    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
9    7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0     NaN      20
10   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
11   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
12   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0     NaN      20
13   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
14   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
15   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [6]:
dept= q("select * from dept")
dept

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

1. List the names of analysts and salesmen.

In [7]:
# MYSQL Query
#SELECT ename,job FROM emp WHERE job in('ANALYST','SALESMAN');
# pandas code
#q("select ename from emp where job in ('ANALYST','SALESMAN')") we can use both way
result = emp[emp['job'].isin(['ANALYST', 'SALESMAN'])][['ename', 'job']]
result

     ename       job
0   DHIRAJ   ANALYST
1     SHAN   ANALYST
3    ALLEN  SALESMAN
4     WARD  SALESMAN
6   MARTIN  SALESMAN
9    SCOTT   ANALYST
11  TURNER  SALESMAN
14    FORD   ANALYST

2. List details of employees who have joined before 30 Sep 81.

In [8]:
# MYSQL Query
# SELECT * FROM emp where hiredate < '1981-09-30';
# pandas code
1.#emp['hiredate'] = pd.to_datetime(emp['hiredate']) # two ways to run the query
    #result = emp.loc[emp['hiredate'] < '1981-09-30']
     #result 
q("select* from emp where hiredate < '1981-09-30'")

   empno   ename       job   mgr    hiredate     sal    comm  deptno
0   7369   SMITH     CLERK  7902  1980-12-17   800.0     NaN      20
1   7499   ALLEN  SALESMAN  7698  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698  1981-02-22  1250.0   500.0      30
3   7566   JONES   MANAGER  7839  1981-04-02  2975.0     NaN      20
4   7654  MARTIN  SALESMAN  7698  1981-09-28  1250.0  1400.0      30
5   7698   BLAKE   MANAGER  7839  1981-05-01  2850.0     NaN      30
6   7782   CLARK   MANAGER  7839  1981-06-09  2450.0     NaN      10
7   7844  TURNER  SALESMAN  7698  1981-09-08  1500.0     0.0      30

3.List names of employees who are not managers.

In [9]:
# MYSQL Query
#  SELECT ename, job FROM emp WHERE job <> 'MANAGER';
# pandas query
#emp[emp['job'] != 'MANAGER'][['ename','job']]
q("select ename from emp where job <>'MANAGER'")

     ename
0   DHIRAJ
1     SHAN
2    SMITH
3    ALLEN
4     WARD
5   MARTIN
6    SCOTT
7     KING
8   TURNER
9    ADAMS
10   JAMES
11    FORD
12  MILLER

4. List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.

In [10]:
# MYSQL Query
#  SELECT ename FROM emp WHERE empno in('7369', '7521', '7934', '7788');
## Equivalent pandas code
#emp[emp['empno'].isin([7369, 7521, 7934, 7788])] [['ename']]
q("select ename from emp where empno in (7369, 7521, 7839, 7934, 7788)")

    ename
0   SMITH
1    WARD
2   SCOTT
3    KING
4  MILLER

5. List employees not belonging to department 30, 40, or 10.

In [11]:
# MYSQL Query
# SELECT ename FROM emp WHERE deptno NOT IN (30,40,10);
# Equivalent pandas code
#emp[~emp['deptno'].isin([30,40,10])][['ename']]
q("select ename from emp where deptno not in (30,40,10)")

   ename
0  SMITH
1  JONES
2  SCOTT
3  ADAMS
4   FORD

6. List employee names for those who have joined between 30 June and 31 Dec.'81

In [12]:
# MYSQL Query
# SELECT ename FROM emp WHERE hiredate between '1981-06-30' and '1981-12-31';
# Equivalent pandas code
#start_date = '1981-06-30'
#end_date = '1981-12-31'
#emp[emp['hiredate'].between(start_date, end_date)][['ename']]
q("select ename from emp where hiredate between '1981-06-30' and '1981-12-31'")

    ename
0  MARTIN
1    KING
2  TURNER
3   JAMES
4    FORD

7. List the different designations in the company.

In [13]:
# MYSQL Query
# SELECT DISTINCT(job) AS designation FROM emp;
# Equivalent pandas code
#emp[['job']].drop_duplicates().rename(columns={'job': 'designation'})
q("select distinct job from emp ")

         job
0    ANALYST
1      CLERK
2   SALESMAN
3    MANAGER
4  PRESIDENT

8. List the names of employees who are not eligible for commission.

In [14]:
# MYSQL Query
# SELECT ename FROM emp WHERE comm IS NULL OR comm = 0;
# Equivalent pandas code
#emp[(emp['comm'].isna ()) | ( emp['comm'] == 0) ][['ename']] 
q("select ename from emp where comm is null or comm= 0")

     ename
0    SMITH
1    JONES
2    BLAKE
3    CLARK
4    SCOTT
5     KING
6   TURNER
7    ADAMS
8    JAMES
9     FORD
10  MILLER

9. List the name and designation of the employee who does not report to anybody.

In [15]:
# MYSQL Query
# SELECT ename AS name, job AS designation FROM emp where mgr IS NULL;
# Equivalent pandas code
#emp[emp['mgr'].isna()][['ename','job']].rename(columns ={'ename':'name', 'job':'designation'})
q("select ename ,job from emp where mgr is null")

  ename        job
0  KING  PRESIDENT

'10. List the employees not assigned to any department.

In [16]:
# MYSQL Query
# SELECT ename FROM emp where deptno IS NULL;
# Equivalent pandas code
#emp[emp['deptno'].isna()][['ename']]
q("select ename from emp where deptno is null")

Empty DataFrame
Columns: [ename]
Index: []

11. List the employees who are eligible for commission.

In [17]:
# MYSQL Query
# SELECT ename FROM emp WHERE comm IS NOT NULL AND comm > 0;
# Equivalent pandas code
#emp[emp['comm'].notna() & ( emp['comm'] != 0)][['ename']] 
q("select ename from emp where comm is not null and comm > 0")

    ename
0  DHIRAJ
1    SHAN
2   ALLEN
3    WARD
4  MARTIN

12. List employees whose names either start or end with “S”.

In [18]:
#MYSQL Query
#SELECT ename FROM emp WHERE ename LIKE 'S%' OR ename LIKE '%S';
#Equivalent pandas code
#emp[emp['ename'].str.contains(r'^S|S$', case=False, na=False)][['ename']]
q("select ename from emp where ename like's%' or ename like '%s'")

   ename
0   SHAN
1  SMITH
2  JONES
3  SCOTT
4  ADAMS
5  JAMES

13. List names of employees whose names have “i” as the second character.

In [19]:
# MYSQL Query
# SELECT ename FROM emp WHERE ename LIKE'_i%';
# Equivalent pandas code
#emp[emp['ename'].str.contains(r'^.i', case=False, na=False)][['ename']] 
q("select ename from emp where ename like '_i%'")

    ename
0    KING
1  MILLER

14. List the number of employees working with the company.

In [20]:
# MYSQL Query
# SELECT COUNT(empno) AS Number_of_Employees FROM emp;
# Equivalent pandas code
#emp[['empno']].count().rename({'empno': 'Nunber_of_Employees'}) # same output as below
#emp['empno'].agg(Nunber_of_Employees='count')
q("select count(*) as total_employees from emp")

   total_employees
0               16

15. List the number of designations available in the EMP table.

In [21]:
# MYSQL Query
# SELECT count(job) AS Number_of_Designation FROM emp;
# Equivalent pandas code
#emp[['job']].count().rename({'job': 'Nunber_of_designations'})
#emp['job'].agg(Nunber_of_designations='count')
q("select count(job) as number_of_designation from emp")

   number_of_designation
0                     16

16. List the total salaries paid to the employees.

In [22]:
# MYSQL Query
# SELECT SUM(sal) AS Total_Salaries FROM emp;
# Equivalent pandas code
#Total_Salaries = emp['sal'].sum()
#print(f'Total_Salaries: {Total_Salaries:.2f}')
#emp['sal'].agg(Total_Salaries='sum')
q("select sum(sal) as total_payroll from emp")

   total_payroll
0        38025.0

17. List the maximum, minimum and average salary in the company.

In [23]:
# MYSQL Query
# SELECT MAX(sal) AS Maximum_Salary, MIN(sal) AS Minimum_Salary, AVG(Sal) AS Average_salary FROM emp;
# Equivalent pandas code
#emp["sal"].agg(Maximum_Salary="max", Minimum_Salary="min", Average_salary="mean")
q("select max(sal) as max_sal, min(sal) as min_sal, avg(sal) as avg_sal from emp")

   max_sal  min_sal    avg_sal
0   5000.0    800.0  2376.5625

18. List the maximum salary paid to a salesman

In [24]:
# MYSQL Query
# SELECT MAX(sal) FROM emp where job = 'salesman';
# Equivalent pandas code
#emp[emp['job'] == 'SALESMAN']['sal'].agg(Maximum_Salary='max')
q("select max(sal) from emp where job = 'salesman'")

   max(sal)
0    1600.0