## blending

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pprint import pformat

In [6]:
#copy data from clipboard
students = pd.read_clipboard(sep='\t')
students.shape

(25, 11)

In [9]:
students

,RollNo,Name,Gender,Program,State,English,Maths,Python,Tableau,FeeTBP,FeePaid
0,1001,Alex,M,BTech,California,78,91,88,82,18000,14000
1,1002,Emma,F,BTech,California,84,95,92,90,18000,13000
2,1003,Liam,M,BBA,Texas,75,72,68,70,12000,10000
3,1004,Olivia,F,BCom,Florida,88,76,74,79,10000,9000
4,1005,Noah,M,BTech,Texas,69,86,90,87,18000,17000
5,1006,Ava,F,BBA,California,91,83,80,85,12000,11000
6,1007,Ethan,M,BCom,Florida,73,68,65,69,10000,9000
7,1008,Sophia,F,BTech,Texas,86,94,95,93,18000,17000
8,1009,Mason,M,BBA,California,80,77,72,74,12000,10000
9,1010,Isabella,F,BCom,Florida,92,81,78,83,10000,8000
10,1011,James,M,BTech,California,77,89,91,88,18000,17000
11,1012,Mia,F,BBA,Texas,83,75,71,76,12000,11000
12,1013,Benjamin,M,BCom,Florida,70,66,63,67,10000,9000
13,1014,Charlotte,F,BTech,Texas,89,97,96,95,18000,14000
14,1015,Lucas,M,BBA,California,81,79,75,77,12000,11000
15,1016,Amelia,F,BCom,Florida,90,84,79,82,10000,7000
16,1017,Henry,M,BTech,California,76,88,87,84,18000,17000
17,1018,Harper,F,BBA,Texas,87,82,81,86,12000,11000
18,1019,Alexander,M,BCom,Florida,72,69,67,71,10000,9000
19,1020,Evelyn,F,BTech,California,94,96,98,97,18000,16000
20,1021,Daniel,M,BBA,Texas,79,74,70,73,12000,10000
21,1022,Abigail,F,BCom,Florida,85,80,76,81,10000,9000
22,1023,Michael,M,BTech,Texas,74,87,89,86,18000,16000
23,1024,Ella,F,BBA,California,93,85,83,88,12000,9000
24,1025,Jacob,M,BCom,Florida,71,67,64,68,10000,8000

In [10]:
#copy target data : goto sheet
targets = pd.read_clipboard(sep='\t')
targets.shape

(3, 5)

In [13]:
targets

  Program  Target  AnnualFee  Faculty  Budget
0   BTech      20      18000       45  360000
1     BBA      15      12000       25  180000
2    BCom      12      10000       18  120000

In [14]:
students['TotalMarks'] = students['English'] + students['Maths'] + students['Python'] + students['Tableau']
students.head()

,RollNo,Name,Gender,Program,State,English,Maths,Python,Tableau,FeeTBP,FeePaid,TotalMarks
0,1001,Alex,M,BTech,California,78,91,88,82,18000,14000,339
1,1002,Emma,F,BTech,California,84,95,92,90,18000,13000,361
2,1003,Liam,M,BBA,Texas,75,72,68,70,12000,10000,285
3,1004,Olivia,F,BCom,Florida,88,76,74,79,10000,9000,317
4,1005,Noah,M,BTech,Texas,69,86,90,87,18000,17000,332

In [15]:
students['avgPython'] = students.groupby('Program')['Python'].transform('mean').round(1)
students.head()

,RollNo,Name,Gender,Program,State,English,Maths,Python,Tableau,FeeTBP,FeePaid,TotalMarks,avgPython
0,1001,Alex,M,BTech,California,78,91,88,82,18000,14000,339,91.8
1,1002,Emma,F,BTech,California,84,95,92,90,18000,13000,361,91.8
2,1003,Liam,M,BBA,Texas,75,72,68,70,12000,10000,285,75.0
3,1004,Olivia,F,BCom,Florida,88,76,74,79,10000,9000,317,70.8
4,1005,Noah,M,BTech,Texas,69,86,90,87,18000,17000,332,91.8

In [16]:
## LOD : {FIXED [Program] : AVG([TotalMarks]) }
lod2 = students.groupby('Program').agg({'TotalMarks':'mean'}).reset_index().round(1)
lod2

  Program  TotalMarks
0     BBA       315.6
1    BCom       299.8
2   BTech       353.1

In [17]:
# Difference of Total Marks against Average Marks of class depending upon the program
students['progAvg'] = students.groupby('Program')['TotalMarks'].transform('mean').round(1)
students.head()

,RollNo,Name,Gender,Program,State,English,Maths,Python,Tableau,FeeTBP,FeePaid,TotalMarks,avgPython,progAvg
0,1001,Alex,M,BTech,California,78,91,88,82,18000,14000,339,91.8,353.1
1,1002,Emma,F,BTech,California,84,95,92,90,18000,13000,361,91.8,353.1
2,1003,Liam,M,BBA,Texas,75,72,68,70,12000,10000,285,75.0,315.6
3,1004,Olivia,F,BCom,Florida,88,76,74,79,10000,9000,317,70.8,299.8
4,1005,Noah,M,BTech,Texas,69,86,90,87,18000,17000,332,91.8,353.1

In [18]:
students["Diff_Total_progAvg"] = ( students["TotalMarks"] - students["progAvg"])
students.head()

,RollNo,Name,Gender,Program,State,English,Maths,Python,Tableau,FeeTBP,FeePaid,TotalMarks,avgPython,progAvg,Diff_Total_progAvg
0,1001,Alex,M,BTech,California,78,91,88,82,18000,14000,339,91.8,353.1,-14.1
1,1002,Emma,F,BTech,California,84,95,92,90,18000,13000,361,91.8,353.1,7.9
2,1003,Liam,M,BBA,Texas,75,72,68,70,12000,10000,285,75.0,315.6,-30.6
3,1004,Olivia,F,BCom,Florida,88,76,74,79,10000,9000,317,70.8,299.8,17.2
4,1005,Noah,M,BTech,Texas,69,86,90,87,18000,17000,332,91.8,353.1,-21.1

In [23]:
students.groupby('Program').agg({'RollNo':'count', 'FeePaid':'sum'}).round(1).reset_index()

  Program  RollNo  FeePaid
0     BBA       8    83000
1    BCom       8    68000
2   BTech       9   141000

In [24]:
#Expressions Way
aggrExpr = {'Admissions' : ('RollNo', 'count'), 'FeeCollected' :('FeePaid','sum')}
students.groupby('Program').agg(**aggrExpr).round(1).reset_index()

  Program  Admissions  FeeCollected
0     BBA           8         83000
1    BCom           8         68000
2   BTech           9        141000

In [25]:
# Group1
blend1 = students.groupby('Program').agg(Admissions = ('RollNo', 'count'), FeeCollected = ('FeePaid','sum')).round(0).reset_index()
blend1

  Program  Admissions  FeeCollected
0     BBA           8         83000
1    BCom           8         68000
2   BTech           9        141000

In [26]:
targets

  Program  Target  AnnualFee  Faculty  Budget
0   BTech      20      18000       45  360000
1     BBA      15      12000       25  180000
2    BCom      12      10000       18  120000

In [27]:
blend2 = targets.copy()
blend2

  Program  Target  AnnualFee  Faculty  Budget
0   BTech      20      18000       45  360000
1     BBA      15      12000       25  180000
2    BCom      12      10000       18  120000

In [28]:
blending = pd.merge(blend1, blend2, on='Program')
blending

  Program  Admissions  FeeCollected  Target  AnnualFee  Faculty  Budget
0     BBA           8         83000      15      12000       25  180000
1    BCom           8         68000      12      10000       18  120000
2   BTech           9        141000      20      18000       45  360000

In [29]:
# Pipeline style adding columns
blending.assign(admAch = lambda x: round(100 * x['Admissions'] / x['Target']),budgetAch = lambda x : round(100 * x['FeeCollected']/x['Budget']))

,Program,Admissions,FeeCollected,Target,AnnualFee,Faculty,Budget,admAch,budgetAch
0,BBA,8,83000,15,12000,25,180000,53.0,46.0
1,BCom,8,68000,12,10000,18,120000,67.0,57.0
2,BTech,9,141000,20,18000,45,360000,45.0,39.0

In [30]:
blending['Productivity_Adm'] = blending['Admissions'] / blending['Target']
blending

,Program,Admissions,FeeCollected,Target,AnnualFee,Faculty,Budget,Productivity_Adm
0,BBA,8,83000,15,12000,25,180000,0.533333
1,BCom,8,68000,12,10000,18,120000,0.666667
2,BTech,9,141000,20,18000,45,360000,0.450000

In [31]:
30000/80000

0.375