In [37]:
import pandas as pd

In [38]:
from pydataset import data

In [39]:
data={'student':['alisha','alisha','bob','jackie','jhony','rocky'],
     'subject':['math','science','math','science','english','math'],
     'score':[90,85,80,95,60,70,]}

In [40]:
df= pd.DataFrame(data)

In [41]:
df

  student  subject  score
0  alisha     math     90
1  alisha  science     85
2     bob     math     80
3  jackie  science     95
4   jhony  english     60
5   rocky     math     70

In [44]:
df.head()

  student  subject  score
0  alisha     math     90
1  alisha  science     85
2     bob     math     80
3  jackie  science     95
4   jhony  english     60

In [45]:
df.tail()

  student  subject  score
1  alisha  science     85
2     bob     math     80
3  jackie  science     95
4   jhony  english     60
5   rocky     math     70

In [46]:
df.head(2)

  student  subject  score
0  alisha     math     90
1  alisha  science     85

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   student  6 non-null      object
 1   subject  6 non-null      object
 2   score    6 non-null      int64
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [48]:
pivoted_df= df.pivot(index='student',columns='subject', values='score')

In [49]:
print(pivoted_df)

subject  english  math  science
student
alisha       NaN  90.0     85.0
bob          NaN  80.0      NaN
jackie       NaN   NaN     95.0
jhony       60.0   NaN      NaN
rocky        NaN  70.0      NaN

In [50]:
df.pivot_table(index='student',columns='subject',values='score',fill_value=0)

subject  english  math  science
student
alisha       0.0  90.0     85.0
bob          0.0  80.0      0.0
jackie       0.0   0.0     95.0
jhony       60.0   0.0      0.0
rocky        0.0  70.0      0.0

In [58]:
df.pivot_table(index='student',columns='subject',values='score',
               aggfunc='sum',fill_value=0,observed= True)

subject  english  math  science
student
alisha         0    90       85
bob            0    80        0
jackie         0     0       95
jhony         60     0        0
rocky          0    70        0