In [4]:
import pandas as pd
import numpy as np

In [5]:
from pydataset import data

In [8]:
data=[
    [1, 'Taheera', 70, 86],
    [2, 'Aelita', 56, 90],
    [3, 'Khulan', 87, 90],
    [4, 'Batgerel', 71, 79],
    [5, 'Manisha', 88, 76],
]
df = pd.DataFrame(data, columns=['Rollno','Name', 'Maths', 'English'])

In [9]:
df

   Rollno      Name  Maths  English
0       1   Taheera     70       86
1       2    Aelita     56       90
2       3    Khulan     87       90
3       4  Batgerel     71       79
4       5   Manisha     88       76

# wide to long

In [11]:
df_long = df.melt(id_vars=['Rollno','Name'], 
                 value_vars=['Maths','English'], 
                 var_name='Subject', 
                 value_name='Marks')
df_long

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3    Khulan    Maths     87
3       4  Batgerel    Maths     71
4       5   Manisha    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3    Khulan  English     90
8       4  Batgerel  English     79
9       5   Manisha  English     76

In [15]:
wide_df = df_long.pivot(index=['Rollno','Name'], columns='Subject',values='Marks').reset_index(drop= False).rename_axis(None, axis=1)
wide_df

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3    Khulan       90     87
3       4  Batgerel       79     71
4       5   Manisha       76     88

In [18]:
wide_df2 = df_long.pivot_table(index =['Rollno','Name'],columns='Subject',values='Marks',
                               aggfunc='sum').reset_index(drop= False).rename_axis(None,axis=1)
wide_df2

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3    Khulan       90     87
3       4  Batgerel       79     71
4       5   Manisha       76     88

In [19]:
df_long

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3    Khulan    Maths     87
3       4  Batgerel    Maths     71
4       5   Manisha    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3    Khulan  English     90
8       4  Batgerel  English     79
9       5   Manisha  English     76

In [21]:
df_long.groupby('Subject') ['Marks'].agg(['sum','mean','count'])

         sum  mean  count
Subject
English  421  84.2      5
Maths    372  74.4      5

In [26]:
df[['Maths','English',]]. mean()

Maths      74.4
English    84.2
dtype: float64

In [27]:
df.dtypes

Rollno      int64
Name       object
Maths       int64
English     int64
dtype: object

In [28]:
df.select_dtypes(include='number').mean()

Rollno      3.0
Maths      74.4
English    84.2
dtype: float64

# Missing Values

In [29]:
import numpy as np
data = [
    [1, 'Taheera', None, 86],
    [2, 'Aelita', 56, 90],
    [3, 'Khulan', np.nan, None],
    [4, 'Batgerel', 71, 79],
    [5, 'Manisha', np.nan, 76],
]

df = pd.DataFrame(data, columns=['Rollno','Name', 'Maths', 'English'])
df

   Rollno      Name  Maths  English
0       1   Taheera    NaN     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan    NaN      NaN
3       4  Batgerel   71.0     79.0
4       5   Manisha    NaN     76.0

In [31]:
df.isna().sum()

Rollno     0
Name       0
Maths      3
English    1
dtype: int64

In [32]:
df.isna().sum(axis=1)

0    1
1    0
2    2
3    0
4    1
dtype: int64

In [33]:
df.fillna(40)

   Rollno      Name  Maths  English
0       1   Taheera   40.0     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan   40.0     40.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   40.0     76.0

In [36]:
df['Maths']. mean()

np.float64(63.5)

In [40]:
df['Maths']= df['Maths']. fillna(df['Maths'].mean())
df

   Rollno      Name  Maths  English
0       1   Taheera   63.5     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan   63.5      NaN
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [41]:
df['English']= df['English']. fillna(df['English'].min())
df

   Rollno      Name  Maths  English
0       1   Taheera   63.5     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan   63.5     76.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [47]:
df.loc[df['Rollno']== 1,'Maths'] = 88
df.loc[df['Rollno']== 3,['Maths','English']] = [100,100]
df

   Rollno      Name  Maths  English
0       1   Taheera   88.0     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan  100.0    100.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [48]:
df

   Rollno      Name  Maths  English
0       1   Taheera   88.0     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan  100.0    100.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [49]:
data2 = [
    [1, 'Taheera', 77],
    [2, 'Aelita', 77],
    [3, 'Khulan', 77],
    [4, 'Batgerel', 77],
    [5, 'Manisha', 77],
]

df2 = pd.DataFrame(data2, columns=['Rollno','Name', 'French'])
df2

   Rollno      Name  French
0       1   Taheera      77
1       2    Aelita      77
2       3    Khulan      77
3       4  Batgerel      77
4       5   Manisha      77

In [50]:
df

   Rollno      Name  Maths  English
0       1   Taheera   88.0     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan  100.0    100.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [51]:
df3= pd.merge(df,df2,on=[ 'Rollno','Name'])
df3

   Rollno      Name  Maths  English  French
0       1   Taheera   88.0     86.0      77
1       2    Aelita   56.0     90.0      77
2       3    Khulan  100.0    100.0      77
3       4  Batgerel   71.0     79.0      77
4       5   Manisha   63.5     76.0      77