# pandas

In [6]:
import pandas as pd

In [7]:
from pydataset import data

initiated datasets repo at: C:\Users\rajia\.pydataset/

In [10]:
mtcars = data('mtcars')
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [22]:
mtcars[0:10:3]

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Duster 360      14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
Merc 280        19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4

In [24]:
type(mtcars)

pandas.core.frame.DataFrame

In [27]:
pd.DataFrame

pandas.core.frame.DataFrame

In [30]:
mtcars.head(n=3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [31]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [33]:
mtcars.tail(5)

                 mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

In [35]:
mtcars.sample(3)

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Duster 360      14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [36]:
mtcars.shape

(32, 11)

In [38]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [12]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.0+ KB

In [39]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [40]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object')

In [41]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

# Summary

In [13]:
mtcars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [42]:
mtcars.mpg.describe()

count    32.000000
mean     20.090625
std       6.026948
min      10.400000
25%      15.425000
50%      19.200000
75%      22.800000
max      33.900000
Name: mpg, dtype: float64

In [43]:
mtcars.describe(include='all')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [44]:
mtcars.cyl.value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [45]:
mtcars.nunique()

mpg     25
cyl      3
disp    27
hp      22
drat    22
wt      29
qsec    30
vs       2
am       2
gear     3
carb     6
dtype: int64

In [47]:
mtcars.gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [48]:
mtcars['am'].value_counts()

am
0    19
1    13
Name: count, dtype: int64

In [16]:
mtcars[:5]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [17]:
mtcars[25:]

                 mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Fiat X1-9       27.3    4   79.0   66  4.08  1.935  18.9   1   1     4     1
Porsche 914-2   26.0    4  120.3   91  4.43  2.140  16.7   0   1     5     2
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

In [18]:
mtcars[::-1]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4

In [49]:
mtcars.isnull()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,False,False,False,False,False,False,False,False,False,False,False
Mazda RX4 Wag,False,False,False,False,False,False,False,False,False,False,False
Datsun 710,False,False,False,False,False,False,False,False,False,False,False
Hornet 4 Drive,False,False,False,False,False,False,False,False,False,False,False
Hornet Sportabout,False,False,False,False,False,False,False,False,False,False,False
Valiant,False,False,False,False,False,False,False,False,False,False,False
Duster 360,False,False,False,False,False,False,False,False,False,False,False
Merc 240D,False,False,False,False,False,False,False,False,False,False,False
Merc 230,False,False,False,False,False,False,False,False,False,False,False
Merc 280,False,False,False,False,False,False,False,False,False,False,False
Merc 280C,False,False,False,False,False,False,False,False,False,False,False
Merc 450SE,False,False,False,False,False,False,False,False,False,False,False
Merc 450SL,False,False,False,False,False,False,False,False,False,False,False
Merc 450SLC,False,False,False,False,False,False,False,False,False,False,False
Cadillac Fleetwood,False,False,False,False,False,False,False,False,False,False,False
Lincoln Continental,False,False,False,False,False,False,False,False,False,False,False
Chrysler Imperial,False,False,False,False,False,False,False,False,False,False,False
Fiat 128,False,False,False,False,False,False,False,False,False,False,False
Honda Civic,False,False,False,False,False,False,False,False,False,False,False
Toyota Corolla,False,False,False,False,False,False,False,False,False,False,False
Toyota Corona,False,False,False,False,False,False,False,False,False,False,False
Dodge Challenger,False,False,False,False,False,False,False,False,False,False,False
AMC Javelin,False,False,False,False,False,False,False,False,False,False,False
Camaro Z28,False,False,False,False,False,False,False,False,False,False,False
Pontiac Firebird,False,False,False,False,False,False,False,False,False,False,False
Fiat X1-9,False,False,False,False,False,False,False,False,False,False,False
Porsche 914-2,False,False,False,False,False,False,False,False,False,False,False
Lotus Europa,False,False,False,False,False,False,False,False,False,False,False
Ford Pantera L,False,False,False,False,False,False,False,False,False,False,False
Ferrari Dino,False,False,False,False,False,False,False,False,False,False,False
Maserati Bora,False,False,False,False,False,False,False,False,False,False,False
Volvo 142E,False,False,False,False,False,False,False,False,False,False,False

In [50]:
mtcars.isnull().sum().sum()

np.int64(0)

In [51]:
mtcars.isnull().head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,False,False,False,False,False,False,False,False,False,False,False
Mazda RX4 Wag,False,False,False,False,False,False,False,False,False,False,False
Datsun 710,False,False,False,False,False,False,False,False,False,False,False
Hornet 4 Drive,False,False,False,False,False,False,False,False,False,False,False
Hornet Sportabout,False,False,False,False,False,False,False,False,False,False,False

In [52]:
mtcars.isnull().sum (axis=0) #counting missing values, columns wise, axis=0 (Columns)

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [53]:
mtcars.isnull().sum (axis=1) #counting missing values, rowwise, axis=1 (rows)

Mazda RX4              0
Mazda RX4 Wag          0
Datsun 710             0
Hornet 4 Drive         0
Hornet Sportabout      0
Valiant                0
Duster 360             0
Merc 240D              0
Merc 230               0
Merc 280               0
Merc 280C              0
Merc 450SE             0
Merc 450SL             0
Merc 450SLC            0
Cadillac Fleetwood     0
Lincoln Continental    0
Chrysler Imperial      0
Fiat 128               0
Honda Civic            0
Toyota Corolla         0
Toyota Corona          0
Dodge Challenger       0
AMC Javelin            0
Camaro Z28             0
Pontiac Firebird       0
Fiat X1-9              0
Porsche 914-2          0
Lotus Europa           0
Ford Pantera L         0
Ferrari Dino           0
Maserati Bora          0
Volvo 142E             0
dtype: int64

In [54]:
mtcars.notnull().sum(axis=0)  #for each column, count non-missing values, 32

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64

In [55]:
mtcars.sum(axis=1)

Mazda RX4              328.980
Mazda RX4 Wag          329.795
Datsun 710             259.580
Hornet 4 Drive         426.135
Hornet Sportabout      590.310
Valiant                385.540
Duster 360             656.920
Merc 240D              270.980
Merc 230               299.570
Merc 280               350.460
Merc 280C              349.660
Merc 450SE             510.740
Merc 450SL             511.500
Merc 450SLC            509.850
Cadillac Fleetwood     728.560
Lincoln Continental    726.644
Chrysler Imperial      725.695
Fiat 128               213.850
Honda Civic            195.165
Toyota Corolla         206.955
Toyota Corona          273.775
Dodge Challenger       519.650
AMC Javelin            506.085
Camaro Z28             646.280
Pontiac Firebird       631.175
Fiat X1-9              208.215
Porsche 914-2          272.570
Lotus Europa           273.683
Ford Pantera L         670.690
Ferrari Dino           379.590
Maserati Bora          694.710
Volvo 142E             288.890
dtype: float64

In [56]:
mtcars.notnull().sum(axis=1)  # for each row, count of non-missing values, 11

Mazda RX4              11
Mazda RX4 Wag          11
Datsun 710             11
Hornet 4 Drive         11
Hornet Sportabout      11
Valiant                11
Duster 360             11
Merc 240D              11
Merc 230               11
Merc 280               11
Merc 280C              11
Merc 450SE             11
Merc 450SL             11
Merc 450SLC            11
Cadillac Fleetwood     11
Lincoln Continental    11
Chrysler Imperial      11
Fiat 128               11
Honda Civic            11
Toyota Corolla         11
Toyota Corona          11
Dodge Challenger       11
AMC Javelin            11
Camaro Z28             11
Pontiac Firebird       11
Fiat X1-9              11
Porsche 914-2          11
Lotus Europa           11
Ford Pantera L         11
Ferrari Dino           11
Maserati Bora          11
Volvo 142E             11
dtype: int64

In [57]:
32*11

352