In [136]:
import numpy as np
import pandas as pd

In [137]:
pd.set_option('display.max_columns', None)

In [138]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [139]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [140]:
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [141]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [142]:
mtcars['mpg'].max()

33.9

In [143]:
mtcars['mpg'].min()

10.4

In [144]:
mtcars[mtcars['mpg'] > 30]. sort_values ('mpg',ascending=False)

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2

In [145]:
mtcars[mtcars['mpg'] == mtcars['mpg'].max()]

                 mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [146]:
mtcars[mtcars['mpg'] >= mtcars['mpg'].min ()]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [147]:
bins = [0, 17, 29, mtcars['mpg'].max()]
labels = ['Low', 'Medium', 'High']

In [148]:
mtcars.describe ()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [149]:
bins = [0, 70, 150, 250, mtcars['hp'].max()]
labels = ['Low', 
          'Medium', 'High', 'VeryHigh']
mtcars['hp_level'] = pd.cut(mtcars['hp'], bins=bins, labels=labels, include_lowest=True)

In [150]:
mtcars['hp_level'].value_counts()

hp_level
Medium      14
High        11
Low          5
VeryHigh     2
Name: count, dtype: int64

In [151]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,High

In [152]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,High

In [153]:
mtcars.groupby('mpg_level')['mpg'].count()

KeyError: 'mpg_level'

In [154]:
mtcars.mpg_level.value_counts()

AttributeError: 'DataFrame' object has no attribute 'mpg_level'

In [155]:
mtcars['vs'] = mtcars['vs'].map({0: 'Vshaped', 1: 'Straight'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High

In [156]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object')

In [157]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High

In [182]:
mtcars['car_name'] = mtcars.index

In [159]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High,Hornet Sportabout

In [160]:
mtcars.dtypes

mpg          float64
cyl            int64
disp         float64
hp             int64
drat         float64
wt           float64
qsec         float64
vs            object
am             int64
gear           int64
carb           int64
hp_level    category
car_name      object
dtype: object

In [161]:
print(len(mtcars[mtcars['mpg'] > 25]))
mtcars[mtcars['mpg'] > 25]

6

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,1,4,1,Low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,1,4,2,Low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,1,4,1,Low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,1,4,1,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,1,5,2,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,1,5,2,Medium,Lotus Europa

In [162]:
mtcars[mtcars['wt'] >= 5]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,0,3,4,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,0,3,4,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,0,3,4,High,Chrysler Imperial

In [163]:
mtcars[mtcars['mpg_level'] == 'High' ]

KeyError: 'mpg_level'

In [164]:
mtcars.query("mpg < 23")

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,0,3,1,Medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,0,3,4,High,Duster 360
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,0,4,2,Medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,0,4,4,Medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,0,4,4,Medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,0,3,3,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,0,3,3,High,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,0,3,3,High,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,0,3,4,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,0,3,4,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,0,3,4,High,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,0,3,1,Medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,0,3,2,Medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,0,3,2,Medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,0,3,4,High,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,0,3,2,High,Pontiac Firebird
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,1,5,4,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,1,5,6,High,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,1,5,8,VeryHigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,1,4,2,Medium,Volvo 142E

In [165]:
mtcars.filter(items =['mpg','hp'])

                      mpg   hp
Mazda RX4            21.0  110
Mazda RX4 Wag        21.0  110
Datsun 710           22.8   93
Hornet 4 Drive       21.4  110
Hornet Sportabout    18.7  175
Valiant              18.1  105
Duster 360           14.3  245
Merc 240D            24.4   62
Merc 230             22.8   95
Merc 280             19.2  123
Merc 280C            17.8  123
Merc 450SE           16.4  180
Merc 450SL           17.3  180
Merc 450SLC          15.2  180
Cadillac Fleetwood   10.4  205
Lincoln Continental  10.4  215
Chrysler Imperial    14.7  230
Fiat 128             32.4   66
Honda Civic          30.4   52
Toyota Corolla       33.9   65
Toyota Corona        21.5   97
Dodge Challenger     15.5  150
AMC Javelin          15.2  150
Camaro Z28           13.3  245
Pontiac Firebird     19.2  175
Fiat X1-9            27.3   66
Porsche 914-2        26.0   91
Lotus Europa         30.4  113
Ford Pantera L       15.8  264
Ferrari Dino         19.7  175
Maserati Bora        15.0  335
Volvo 142E           21.4  109

In [166]:
mtcars[mtcars['am'] == 'auto']

Empty DataFrame
Columns: [mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb, hp_level, car_name]
Index: []

In [167]:
mtcars[(mtcars['am'] == 'auto') & (mtcars['cyl'] != '5') & (mtcars['mpg'] > 22 )]

Empty DataFrame
Columns: [mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb, hp_level, car_name]
Index: []

In [168]:
mtcars[mtcars['mpg'].between(left=23, right=26.1, inclusive='left')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,Straight,0,4,2,Low,Merc 240D
Porsche 914-2,26.0,4,120.3,91,4.43,2.14,16.7,Vshaped,1,5,2,Medium,Porsche 914-2

In [169]:
mtcars[mtcars['mpg'].between(23, 30, inclusive='neither')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.0,Straight,0,4,2,Low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.9,Straight,1,4,1,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,Vshaped,1,5,2,Medium,Porsche 914-2

In [170]:
mtcars[mtcars['mpg'].between(23, 30) & (mtcars['am'] == 'manual')

_IncompleteInputError: incomplete input (3877049995.py, line 1)

In [171]:
mtcars[mtcars['gear'].isin([4,5])]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,0,4,2,Low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,0,4,2,Medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,0,4,4,Medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,0,4,4,Medium,Merc 280C
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,1,4,1,Low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,1,4,2,Low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,1,4,1,Low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,1,4,1,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,1,5,2,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,1,5,2,Medium,Lotus Europa
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,1,5,4,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,1,5,6,High,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,1,5,8,VeryHigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,1,4,2,Medium,Volvo 142E

In [172]:
mtcars[ (mtcars['gear'].isin([4, 5]))

_IncompleteInputError: incomplete input (233319815.py, line 1)

In [173]:
mtcars[~mtcars['gear'].isin([4, 5])]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,0,3,1,Medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,0,3,4,High,Duster 360
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,0,3,3,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,0,3,3,High,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,0,3,3,High,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,0,3,4,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,0,3,4,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,0,3,4,High,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,0,3,1,Medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,0,3,2,Medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,0,3,2,Medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,0,3,4,High,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,0,3,2,High,Pontiac Firebird

# Select dtypes

In [174]:
mtcars.dtypes

mpg          float64
cyl            int64
disp         float64
hp             int64
drat         float64
wt           float64
qsec         float64
vs            object
am             int64
gear           int64
carb           int64
hp_level    category
car_name      object
dtype: object

In [175]:
mtcars.select_dtypes(include='number')

                      mpg  cyl   disp   hp  drat     wt   qsec  am  gear  carb
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   1     4     4
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   1     4     4
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1     4     1
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   0     3     1
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0     3     2
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   0     3     1
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0     3     4
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   0     4     2
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   0     4     2
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   0     4     4
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   0     4     4
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0     3     3
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0     3     3
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0     3     3
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0     3     4
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0     3     4
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0     3     4
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1     4     1
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1     4     2
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1     4     1
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   0     3     1
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0     3     2
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0     3     2
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0     3     4
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0     3     2
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1     4     1
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   1     5     2
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1     5     2
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   1     5     4
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   1     5     6
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   1     5     8
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1     4     2

In [176]:
mtcars.select_dtypes(include='category').head()

                  hp_level
Mazda RX4           Medium
Mazda RX4 Wag       Medium
Datsun 710          Medium
Hornet 4 Drive      Medium
Hornet Sportabout     High

In [177]:
mtcars.select_dtypes(include='object').head()

                         vs           car_name
Mazda RX4           Vshaped          Mazda RX4
Mazda RX4 Wag       Vshaped      Mazda RX4 Wag
Datsun 710         Straight         Datsun 710
Hornet 4 Drive     Straight     Hornet 4 Drive
Hornet Sportabout   Vshaped  Hornet Sportabout

# sort values

In [178]:
mtcars.sort_values(by='mpg', ascending=True, inplace=True)

In [179]:
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,0,3,4,High,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,0,3,4,High,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,0,3,4,High,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,0,3,4,High,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,0,3,4,High,Chrysler Imperial
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,1,5,8,VeryHigh,Maserati Bora
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,0,3,3,High,Merc 450SLC
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,0,3,2,Medium,AMC Javelin
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,0,3,2,Medium,Dodge Challenger
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,1,5,4,VeryHigh,Ford Pantera L
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,0,3,3,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,0,3,3,High,Merc 450SL
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,0,4,4,Medium,Merc 280C
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,0,3,1,Medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High,Hornet Sportabout
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,0,4,4,Medium,Merc 280
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,0,3,2,High,Pontiac Firebird
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,1,5,6,High,Ferrari Dino
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium,Mazda RX4 Wag
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium,Hornet 4 Drive
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,1,4,2,Medium,Volvo 142E
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,0,3,1,Medium,Toyota Corona
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,0,4,2,Medium,Merc 230
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,0,4,2,Low,Merc 240D
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,1,5,2,Medium,Porsche 914-2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,1,4,1,Low,Fiat X1-9
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,1,5,2,Medium,Lotus Europa
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,1,4,2,Low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,1,4,1,Low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,1,4,1,Low,Toyota Corolla

In [180]:
mtcars.sort_values(['gear','mpg'])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,0,3,4,High,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,0,3,4,High,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,0,3,4,High,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,0,3,4,High,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,0,3,4,High,Chrysler Imperial
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,0,3,3,High,Merc 450SLC
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,0,3,2,Medium,AMC Javelin
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,0,3,2,Medium,Dodge Challenger
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,0,3,3,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,0,3,3,High,Merc 450SL
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,0,3,1,Medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High,Hornet Sportabout
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,0,3,2,High,Pontiac Firebird
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium,Hornet 4 Drive
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,0,3,1,Medium,Toyota Corona
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,0,4,4,Medium,Merc 280C
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,0,4,4,Medium,Merc 280
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium,Mazda RX4 Wag
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,1,4,2,Medium,Volvo 142E
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,0,4,2,Medium,Merc 230
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,0,4,2,Low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,1,4,1,Low,Fiat X1-9
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,1,4,2,Low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,1,4,1,Low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,1,4,1,Low,Toyota Corolla
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,1,5,8,VeryHigh,Maserati Bora
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,1,5,4,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,1,5,6,High,Ferrari Dino
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,1,5,2,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,1,5,2,Medium,Lotus Europa

In [181]:
mtcars.sort_values(['gear','mpg'], ascending=[False,True])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp_level,car_name
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,1,5,8,VeryHigh,Maserati Bora
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,1,5,4,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,1,5,6,High,Ferrari Dino
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,1,5,2,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,1,5,2,Medium,Lotus Europa
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,0,4,4,Medium,Merc 280C
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,0,4,4,Medium,Merc 280
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,1,4,4,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,1,4,4,Medium,Mazda RX4 Wag
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,1,4,2,Medium,Volvo 142E
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,0,4,2,Medium,Merc 230
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1,Medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,0,4,2,Low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,1,4,1,Low,Fiat X1-9
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,1,4,2,Low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,1,4,1,Low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,1,4,1,Low,Toyota Corolla
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,0,3,4,High,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,0,3,4,High,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,0,3,4,High,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,0,3,4,High,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,0,3,4,High,Chrysler Imperial
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,0,3,3,High,Merc 450SLC
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,0,3,2,Medium,AMC Javelin
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,0,3,2,Medium,Dodge Challenger
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,0,3,3,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,0,3,3,High,Merc 450SL
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,0,3,1,Medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,0,3,2,High,Hornet Sportabout
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,0,3,2,High,Pontiac Firebird
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1,Medium,Hornet 4 Drive
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,0,3,1,Medium,Toyota Corona