In [84]:
import numpy as np
import pandas as pd

In [85]:
pd.set_option ('display.max_columns', None)

In [86]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [87]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [88]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [89]:
mtcars = data('mtcars')
mtcars = mtcars.astype({ 'cyl':'category', 'vs': 'category',  'carb': 'category',  
                         'am':   'category',  'gear':  'category' } )

In [90]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [91]:
mtcars.head()

                    mpg cyl   disp   hp  drat     wt   qsec vs am gear carb
Mazda RX4          21.0   6  160.0  110  3.90  2.620  16.46  0  1    4    4
Mazda RX4 Wag      21.0   6  160.0  110  3.90  2.875  17.02  0  1    4    4
Datsun 710         22.8   4  108.0   93  3.85  2.320  18.61  1  1    4    1
Hornet 4 Drive     21.4   6  258.0  110  3.08  3.215  19.44  1  0    3    1
Hornet Sportabout  18.7   8  360.0  175  3.15  3.440  17.02  0  0    3    2

In [92]:
mtcars['vs'] = mtcars['vs'].map({0: 'vshaped', 1: 'Straight'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,0,3,2

In [93]:
mtcars['am'] = mtcars['am'].map({0:'auto',1: 'manual'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,auto,3,2

In [94]:
mtcars[mtcars['mpg'] > 30].sort_values('mpg', ascending=False)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2

In [95]:
mtcars['cyl'].value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

# pivot table
-index: what goes down the rows
-columns: what goes accross the top
-values: what fills the table 
-aggfunc: how to summarice if there duplicates

In [96]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,auto,3,2

In [97]:
mtcars.pivot_table(values='mpg',index='gear',observed = False)

            mpg
gear
3     16.106667
4     24.533333
5     21.380000

In [98]:
mtcars.pivot_table(values= 'hp', index= 'cyl',observed= False)

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [99]:
mtcars.pivot_table(values= ['mpg','hp'],index=['cyl','am'], observed= True,
                    aggfunc=['sum','mean','count']).reset_index()

  cyl      am   sum               mean            count
                 hp    mpg          hp        mpg    hp mpg
0   4    auto   254   68.7   84.666667  22.900000     3   3
1   4  manual   655  224.6   81.875000  28.075000     8   8
2   6    auto   461   76.5  115.250000  19.125000     4   4
3   6  manual   395   61.7  131.666667  20.566667     3   3
4   8    auto  2330  180.6  194.166667  15.050000    12  12
5   8  manual   599   30.8  299.500000  15.400000     2   2

In [100]:
pd.pivot_table(data= mtcars,observed= False,
               index= 'gear',
               values='mpg',
               aggfunc= 'median')

       mpg
gear
3     15.5
4     22.8
5     19.7

In [103]:
piovt1= pd.pivot_table(data=mtcars,observed= False,
                      index='gear',
                      columns='am',
                      values='mpg',
                      aggfunc='mean')

In [105]:
piovt1

am         auto  manual
gear
3     16.106667     NaN
4     21.050000  26.275
5           NaN  21.380

In [106]:
print(mtcars.am.value_counts(),mtcars.cyl.value_counts())

am
auto      19
manual    13
Name: count, dtype: int64 cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [116]:
pd.pivot_table( observed=True , data= mtcars,  index='gear',  columns='am', \
                values='mpg',
                aggfunc=['mean', 'max', 'min' ,'count','sum']\
              )

           mean           max          min        count           sum
am         auto  manual  auto manual  auto manual  auto manual   auto manual
gear
3     16.106667     NaN  21.5    NaN  10.4    NaN  15.0    NaN  241.6    NaN
4     21.050000  26.275  24.4   33.9  17.8   21.0   4.0    8.0   84.2  210.2
5           NaN  21.380   NaN   30.4   NaN   15.0   NaN    5.0    NaN  106.9

In [123]:
pd.pivot_table(data=mtcars,index='cyl',columns='carb', values='hp',aggfunc=['min','max','count'],observed=False)

        min                                       max                       \
carb      1      2      3      4      6      8      1      2      3      4
cyl
4      65.0   52.0    NaN    NaN    NaN    NaN   97.0  113.0    NaN    NaN
6     105.0    NaN    NaN  110.0  175.0    NaN  110.0    NaN    NaN  123.0
8       NaN  150.0  180.0  205.0    NaN  335.0    NaN  175.0  180.0  264.0

                   count
carb      6      8     1  2  3  4  6  8
cyl
4       NaN    NaN     5  6  0  0  0  0
6     175.0    NaN     2  0  0  4  1  0
8       NaN  335.0     0  4  3  6  0  1

In [125]:
mtcars.pivot_table(
    index= 'gear',
    columns='am',
    values=['hp','mpg'],
    aggfunc='mean')

C:\Users\rajia\AppData\Local\Temp\ipykernel_15768\1821508586.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  mtcars.pivot_table(

              hp                 mpg
am          auto   manual       auto  manual
gear
3     176.133333      NaN  16.106667     NaN
4     100.750000   83.875  21.050000  26.275
5            NaN  195.600        NaN  21.380

In [127]:
mtcars.pivot_table(
    index= 'cyl',
    columns='gear',
    values='hp',
    aggfunc=['min','max']
)

C:\Users\rajia\AppData\Local\Temp\ipykernel_15768\2339848071.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  mtcars.pivot_table(
C:\Users\rajia\AppData\Local\Temp\ipykernel_15768\2339848071.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  mtcars.pivot_table(

        min                  max
gear      3      4      5      3      4      5
cyl
4      97.0   52.0   91.0   97.0  109.0  113.0
6     105.0  110.0  175.0  110.0  123.0  175.0
8     150.0    NaN  264.0  245.0    NaN  335.0

In [130]:
mtcars.pivot_table(
    index= 'cyl',
    columns='carb',
    aggfunc='size',
    fill_value= 0,)

C:\Users\rajia\AppData\Local\Temp\ipykernel_15768\1130470973.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  mtcars.pivot_table(

carb  1  2  3  4  6  8
cyl
4     5  6  0  0  0  0
6     2  0  0  4  1  0
8     0  4  3  6  0  1