In [24]:
from pydataset import data
import pandas as pd
aq= data('airquality')
aq.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5

In [25]:
aq.info() #153 rows, 6 cols

<class 'pandas.core.frame.DataFrame'>
Index: 153 entries, 1 to 153
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    116 non-null    float64
 1   Solar.R  146 non-null    float64
 2   Wind     153 non-null    float64
 3   Temp     153 non-null    int64
 4   Month    153 non-null    int64
 5   Day      153 non-null    int64
dtypes: float64(3), int64(3)
memory usage: 8.4 KB

In [26]:
print(aq.isnull().sum()) # Shows missing values

Ozone      37
Solar.R     7
Wind        0
Temp        0
Month       0
Day         0
dtype: int64

In [27]:
aq.head ()  #original data

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5

In [28]:
#long
aq_long= aq.melt( id_vars=['Month','Day'], value_vars=['Ozone','Solar.R','Wind','Temp'], \
var_name='Measurement',  value_name='Value')
aq_long.head()

   Month  Day Measurement  Value
0      5    1       Ozone   41.0
1      5    2       Ozone   36.0
2      5    3       Ozone   12.0
3      5    4       Ozone   18.0
4      5    5       Ozone    NaN

In [29]:
153*4

612

In [30]:
aq_long  # 153 rows x 4 columns

     Month  Day Measurement  Value
0        5    1       Ozone   41.0
1        5    2       Ozone   36.0
2        5    3       Ozone   12.0
3        5    4       Ozone   18.0
4        5    5       Ozone    NaN
..     ...  ...         ...    ...
607      9   26        Temp   70.0
608      9   27        Temp   77.0
609      9   28        Temp   75.0
610      9   29        Temp   76.0
611      9   30        Temp   68.0

[612 rows x 4 columns]

# melt

In [31]:
pd.melt(frame=aq, id_vars=['Month', 'Day'], value_vars=['Ozone', 'Wind'],\
        var_name='Measurement', value_name='value', col_level=None, ignore_index=True)

     Month  Day Measurement  value
0        5    1       Ozone   41.0
1        5    2       Ozone   36.0
2        5    3       Ozone   12.0
3        5    4       Ozone   18.0
4        5    5       Ozone    NaN
..     ...  ...         ...    ...
301      9   26        Wind    6.9
302      9   27        Wind   13.2
303      9   28        Wind   14.3
304      9   29        Wind    8.0
305      9   30        Wind   11.5

[306 rows x 4 columns]

In [32]:
aq_long.head()

   Month  Day Measurement  Value
0      5    1       Ozone   41.0
1      5    2       Ozone   36.0
2      5    3       Ozone   12.0
3      5    4       Ozone   18.0
4      5    5       Ozone    NaN

In [33]:
# wide
aq_wide = aq_long.pivot_table( index=['Month', 'Day'], columns='Measurement', values='Value' ).reset_index()
aq_wide.head(2)

Measurement  Month  Day  Ozone  Solar.R  Temp  Wind
0                5    1   41.0    190.0  67.0   7.4
1                5    2   36.0    118.0  72.0   8.0

In [37]:
aq.head(2)

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2