In [5]:
from sqlalchemy import create_engine, text
import pymysql
import numpy as np
from pydataset import data
import pydataset
import pandas as pd 
import os

In [10]:
engine1 = create_engine("mysql+pymysql://root:piit2025@localhost:3306/adventureworks")

In [11]:
def q(sql, **params):
 with engine1.connect() as conn:
  return pd.read_sql(text(sql), conn, params=params)

In [12]:
q('show tables')

                 Tables_in_adventureworks
0                                 address
1                             addresstype
2                          awbuildversion
3                         billofmaterials
4                                 contact
5                       contactcreditcard
6                             contacttype
7                           countryregion
8                   countryregioncurrency
9                              creditcard
10                                culture
11                               currency
12                           currencyrate
13                               customer
14                        customeraddress
15                            databaselog
16                             department
17                               document
18                               employee
19                        employeeaddress
20              employeedepartmenthistory
21                     employeepayhistory
22                               errorlog
23                           illustration
24                             individual
25                           jobcandidate
26                               location
27                                product
28                        productcategory
29                     productcosthistory
30                     productdescription
31                        productdocument
32                       productinventory
33                productlistpricehistory
34                           productmodel
35               productmodelillustration
36  productmodelproductdescriptionculture
37                           productphoto
38                    productproductphoto
39                          productreview
40                     productsubcategory
41                          productvendor
42                    purchaseorderdetail
43                    purchaseorderheader
44                       salesorderdetail
45                       salesorderheader
46            salesorderheadersalesreason
47                            salesperson
48                salespersonquotahistory
49                            salesreason
50                           salestaxrate
51                         salesterritory
52                  salesterritoryhistory
53                            scrapreason
54                                  shift
55                             shipmethod
56                       shoppingcartitem
57                           specialoffer
58                    specialofferproduct
59                          stateprovince
60                                  store
61                           storecontact
62                     transactionhistory
63              transactionhistoryarchive
64                            unitmeasure
65                                 vendor
66                          vendoraddress
67                          vendorcontact
68                              workorder
69                       workorderrouting

In [14]:
dep = q("select * from department")
dep

,DepartmentID,Name,GroupName,ModifiedDate
0,1,Engineering,Research and Development,1998-05-31 18:00:00
1,2,Tool Design,Research and Development,1998-05-31 18:00:00
2,3,Sales,Sales and Marketing,1998-05-31 18:00:00
3,4,Marketing,Sales and Marketing,1998-05-31 18:00:00
4,5,Purchasing,Inventory Management,1998-05-31 18:00:00
5,6,Research and Development,Research and Development,1998-05-31 18:00:00
6,7,Production,Manufacturing,1998-05-31 18:00:00
7,8,Production Control,Manufacturing,1998-05-31 18:00:00
8,9,Human Resources,Executive General and Administration,1998-05-31 18:00:00
9,10,Finance,Executive General and Administration,1998-05-31 18:00:00
10,11,Information Services,Executive General and Administration,1998-05-31 18:00:00
11,12,Document Control,Quality Assurance,1998-05-31 18:00:00
12,13,Quality Assurance,Quality Assurance,1998-05-31 18:00:00
13,14,Facilities and Maintenance,Executive General and Administration,1998-05-31 18:00:00
14,15,Shipping and Receiving,Inventory Management,1998-05-31 18:00:00
15,16,Executive,Executive General and Administration,1998-05-31 18:00:00

In [15]:
dep = q( "select name from department")
dep

                          name
0                  Engineering
1                  Tool Design
2                        Sales
3                    Marketing
4                   Purchasing
5     Research and Development
6                   Production
7           Production Control
8              Human Resources
9                      Finance
10        Information Services
11            Document Control
12           Quality Assurance
13  Facilities and Maintenance
14      Shipping and Receiving
15                   Executive

In [17]:
dep = q("select groupname from department")
dep

                               groupname
0               Research and Development
1               Research and Development
2                    Sales and Marketing
3                    Sales and Marketing
4                   Inventory Management
5               Research and Development
6                          Manufacturing
7                          Manufacturing
8   Executive General and Administration
9   Executive General and Administration
10  Executive General and Administration
11                     Quality Assurance
12                     Quality Assurance
13  Executive General and Administration
14                  Inventory Management
15  Executive General and Administration

In [20]:
dep= q("select distinct groupname from department")
dep

                              groupname
0              Research and Development
1                   Sales and Marketing
2                  Inventory Management
3                         Manufacturing
4  Executive General and Administration
5                     Quality Assurance

In [21]:
dep= q("select name from department where groupname = 'Manufacturing'")
dep

                 name
0          Production
1  Production Control

In [22]:
q("select * from employee")

,EmployeeID,NationalIDNumber,ContactID,LoginID,ManagerID,Title,BirthDate,MaritalStatus,Gender,HireDate,SalariedFlag,VacationHours,SickLeaveHours,CurrentFlag,rowguid,ModifiedDate
0,1,14417807,1209,adventure-works\guy1,16.0,Production Technician - WC60,1972-05-15,M,M,1996-07-31,b'\x00',21,30,b'\x01',b'J\xc3\x90\xc3\xa1\xc2\xaa7\xc3\x82tI\xc2\xb4\xc3\x95',2004-07-30 18:00:00
1,2,253022876,1030,adventure-works\kevin0,6.0,Marketing Assistant,1977-06-03,S,M,1997-02-26,b'\x00',42,41,b'\x01',b'@\x02H\x1b\xc3\x80\xc2\x95\x0fA\xc2\xa7\x17\xc3\xab)',2004-07-30 18:00:00
2,3,509647174,1002,adventure-works\roberto0,12.0,Engineering Manager,1964-12-13,M,M,1997-12-12,b'\x01',2,21,b'\x01',"b',\xc3\xbb\xc2\xbb\xc2\x9b\xc2\xbb\xc3\xaf\x17B\xc2\x9a\xc2'",2004-07-30 18:00:00
3,4,112457891,1290,adventure-works\rob0,3.0,Senior Tool Designer,1965-01-23,S,M,1998-01-05,b'\x00',48,80,b'\x01',b'UytY\xc2\xb8\xc2\x87?D\xc2\x8e\xc3\x94\xc3\xb8',2004-07-30 18:00:00
4,5,480168528,1009,adventure-works\thierry0,263.0,Tool Designer,1949-08-29,M,M,1998-01-11,b'\x00',9,24,b'\x01',b'qQ\xc2\x95\x1ds\xc3\xa7\xc2\xadO\xc2\x83\xc2\x82@',2004-07-30 18:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,286,134219713,1022,adventure-works\ranjit0,284.0,Sales Representative,1965-10-31,S,M,2002-07-01,b'\x01',34,37,b'\x01',b'\xc3\xb9\x13B`\x0f\xc3\x9d\xc2\xb4C\xc2\xbd\xc3\x92\xc3',2004-07-30 18:00:00
286,287,90836195,1027,adventure-works\tete0,268.0,Sales Representative,1968-02-06,M,M,2002-11-01,b'\x01',39,39,b'\x01',b'\x00\xc3\x8eg\x0cx\xc3\x9e\x12G\xc2\x90\xc2\x8f\x06\xc2',2004-07-30 18:00:00
287,288,481044938,1012,adventure-works\syed0,273.0,Pacific Sales Manager,1965-02-11,M,M,2003-04-15,b'\x01',20,30,b'\x01',b'\xc3\x9b\xc2\x92\xc3\xb2\xc2\x86<\xc2\xb7\xc2\x9dB\xc2\x99',2004-07-30 18:00:00
288,289,954276278,1023,adventure-works\rachel0,284.0,Sales Representative,1965-08-09,S,F,2003-07-01,b'\x01',35,37,b'\x01',b'Aw\xc2\xbf\xc2\xb9\xc3\x8a\xc3\xa07O\xc2\xac\xc3\x9e',2004-07-30 18:00:00
289,290,758596752,1024,adventure-works\lynn0,288.0,Sales Representative,1961-04-18,S,F,2003-07-01,b'\x01',36,38,b'\x01',b'\x07\xc2\x84\xc2\x9aJ\xc2\x80\xc2\xa6kJ\xc2\x8d\x03Q',2004-07-30 18:00:00

In [23]:
emp=q("select * from employee where ManagerID in (2,3)")
emp

,EmployeeID,NationalIDNumber,ContactID,LoginID,ManagerID,Title,BirthDate,MaritalStatus,Gender,HireDate,SalariedFlag,VacationHours,SickLeaveHours,CurrentFlag,rowguid,ModifiedDate
0,4,112457891,1290,adventure-works\rob0,3,Senior Tool Designer,1965-01-23,S,M,1998-01-05,b'\x00',48,80,b'\x01',b'UytY\xc2\xb8\xc2\x87?D\xc2\x8e\xc3\x94\xc3\xb8',2004-07-30 18:00:00
1,9,695256908,1005,adventure-works\gail0,3,Design Engineer,1942-10-29,M,F,1998-02-06,b'\x01',5,22,b'\x01',b'\t\xc2\xae\xc2\x84\xc3\xac\xc2\xb8\xc3\xb9\x15J\xc2\xb4\xc2',2004-07-30 18:00:00
2,11,998320692,1006,adventure-works\jossef0,3,Design Engineer,1949-04-11,M,M,1998-02-24,b'\x01',6,23,b'\x01',b'\xc3\xb1V\xc2\x90\xc3\xa3\xc3\x95\xc2\x9c\xc2\x8dG\xc2\x89',2004-07-30 18:00:00
3,158,134969118,1049,adventure-works\dylan0,3,Research and Development Manager,1977-03-27,M,M,1999-03-12,b'\x01',61,50,b'\x01',b'\xc3\x8a\xc3\x9eFO\x01\xc3\xaf\xc3\xbdA\xc2\x98)\n',2004-07-30 18:00:00
4,263,974026903,1007,adventure-works\ovidiu0,3,Senior Tool Designer,1968-02-18,S,M,2001-01-05,b'\x00',7,23,b'\x01',b'\x19|\xc2\x8c\xc3\xb6\xc3\x81\xc3\xba\xc2\x8cC\xc2\x9b\xc2',2004-07-30 18:00:00
5,267,42487730,1003,adventure-works\michael8,3,Senior Design Engineer,1969-07-17,S,M,2001-01-30,b'\x01',3,21,b'\x01',b'\xc2\xa4l(F\xc3\x9dF\xc3\x9bM\xc2\x91(\xc2\x85',2004-07-30 18:00:00
6,270,56920285,1004,adventure-works\sharon0,3,Design Engineer,1951-06-03,M,F,2001-02-18,b'\x01',4,22,b'\x01',b'\xc3\x80\xc3\xbd\xc3\xb2T\xc3\x84\xc2\x87e@\xc2\xa7\xc2',2004-07-30 18:00:00

In [25]:
emp=q("SELECT * FROM employee WHERE title ='Facilities manager'")
emp

,EmployeeID,NationalIDNumber,ContactID,LoginID,ManagerID,Title,BirthDate,MaritalStatus,Gender,HireDate,SalariedFlag,VacationHours,SickLeaveHours,CurrentFlag,rowguid,ModifiedDate
0,218,141165819,1274,adventure-works\gary1,148,Facilities Manager,1961-03-21,M,M,2000-01-03,b'\x01',86,63,b'\x01',b'Y\xc3\xac\xc3\xb6b5V\xc3\xb3D\xc2\x9c\xc3\x81-',2004-07-30 18:00:00

In [26]:

emp=q("SELECT * FROM employee WHERE title like 'Facilities manager'")
emp

,EmployeeID,NationalIDNumber,ContactID,LoginID,ManagerID,Title,BirthDate,MaritalStatus,Gender,HireDate,SalariedFlag,VacationHours,SickLeaveHours,CurrentFlag,rowguid,ModifiedDate
0,218,141165819,1274,adventure-works\gary1,148,Facilities Manager,1961-03-21,M,M,2000-01-03,b'\x01',86,63,b'\x01',b'Y\xc3\xac\xc3\xb6b5V\xc3\xb3D\xc2\x9c\xc3\x81-',2004-07-30 18:00:00

In [27]:
emp=q("SELECT Title FROM employee WHERE title like'%manager'")
emp

                               Title
0                Engineering Manager
1                  Marketing Manager
2         Production Control Manager
3            Human Resources Manager
4       Information Services Manager
5                    Finance Manager
6           Document Control Manager
7                   Accounts Manager
8                    Network Manager
9   Research and Development Manager
10         Quality Assurance Manager
11  Research and Development Manager
12                Facilities Manager
13      North American Sales Manager
14                Purchasing Manager
15            European Sales Manager
16             Pacific Sales Manager

In [28]:
emp=q("select * from employee where BirthDate > '1980-01-01'")
emp

,EmployeeID,NationalIDNumber,ContactID,LoginID,ManagerID,Title,BirthDate,MaritalStatus,Gender,HireDate,SalariedFlag,VacationHours,SickLeaveHours,CurrentFlag,rowguid,ModifiedDate
0,37,276751903,1226,adventure-works\simon0,7,Production Technician - WC60,1980-06-17,S,M,1999-01-09,b'\x00',38,39,b'\x01',b'\xc2\x8a\xc3\x934\xc3\xb7\xc2\xb5V\x1eG\xc2\x8d\xc3\xad',2004-07-30 18:00:00
1,54,540688287,1264,adventure-works\tengiz0,90,Control Specialist,1980-05-29,S,M,1999-01-17,b'\x00',76,58,b'\x01',b'\xc2\xb2\xc2\xb3\t\xc3\x86iy\x0cA\xc2\x93Lb\xc3',2004-07-30 18:00:00
2,99,830150469,1158,adventure-works\michael1,87,Production Technician - WC40,1981-02-04,S,M,1999-02-11,b'\x00',70,55,b'\x01',b'\x05\xc3\xb9kAl}\xc2\x92F\xc2\x8f\xc3\x96@\xc3',2004-07-30 18:00:00
3,115,886023130,1094,adventure-works\paul1,108,Production Technician - WC20,1980-12-05,M,M,1999-02-18,b'\x00',6,23,b'\x01',"b'""\xc2\xa6[\xc3\x9c`\xc2\xb8\xc3\xaeA\xc2\xaf\xc2\x92'",2004-07-30 18:00:00
4,120,563680513,1180,adventure-works\angela0,38,Production Technician - WC50,1981-07-01,S,F,1999-02-21,b'\x00',92,66,b'\x01',"b'\xc3\x83\xc3\xa1XIr\xc3\x88""B\xc2\x95N\t\xc3'",2004-07-30 18:00:00
5,136,167554340,1175,adventure-works\kathie0,197,Production Technician - WC45,1980-12-02,M,F,1999-02-28,b'\x00',87,63,b'\x01',b'\xc3\x97\xc2\x84\xc3\xbc%\x13\xc3\xa0\xc2\xb8D\xc2\x82\xc3',2004-07-30 18:00:00
6,155,377784364,1165,adventure-works\alex0,123,Production Technician - WC45,1980-05-14,M,M,1999-03-12,b'\x00',77,58,b'\x01',b'\xc3\x82\xc3\x89k\xc2\xb9%Z\xc2\x9bJ\xc2\x88z\xc3',2004-07-30 18:00:00
7,159,551834634,1063,adventure-works\shane0,21,Production Supervisor - WC45,1980-06-24,S,M,1999-03-12,b'\x00',75,57,b'\x01',b'X\xc3\x83%&*g\x00@\xc2\xadg\xc2\xb8\xc3\x8d',2004-07-30 18:00:00
8,172,273260055,1160,adventure-works\baris0,87,Production Technician - WC40,1980-11-07,S,M,1999-03-19,b'\x00',72,56,b'\x01',b'\xc2\xbfh-#X\xc3\x9f\xc3\xb9H\xc2\x925S\xc2',2004-07-30 18:00:00
9,174,752513276,1219,adventure-works\steve0,18,Production Technician - WC60,1981-05-07,S,M,1999-03-19,b'\x00',31,35,b'\x01',b'\xc3\x97x\xc3\xb6\x12\xc3\x93\xc3\xaa\xc3\xb4L\xc2\x85\x18',2004-07-30 18:00:00
10,179,599942664,1187,adventure-works\chad0,38,Production Technician - WC50,1980-09-04,M,M,1999-03-22,b'\x00',99,69,b'\x01',b'L-\xc2\xa3\xc2\x83%G\xc2\x8fG\xc2\x99\xc2\x97\xc2',2004-07-30 18:00:00
11,202,912141525,1193,adventure-works\elizabeth0,74,Production Technician - WC50,1980-02-26,M,F,1999-04-03,b'\x00',5,22,b'\x01',b'?\xc3\xb7\xc2\xa9bCd/O\xc2\xb8d\x18\x18f',2004-07-30 18:00:00

In [29]:
emp=q("SELECT * FROM Employee WHERE BirthDate BETWEEN '1970-1-1' AND '1980-1-1'")
emp

,EmployeeID,NationalIDNumber,ContactID,LoginID,ManagerID,Title,BirthDate,MaritalStatus,Gender,HireDate,SalariedFlag,VacationHours,SickLeaveHours,CurrentFlag,rowguid,ModifiedDate
0,1,14417807,1209,adventure-works\guy1,16,Production Technician - WC60,1972-05-15,M,M,1996-07-31,b'\x00',21,30,b'\x01',b'J\xc3\x90\xc3\xa1\xc2\xaa7\xc3\x82tI\xc2\xb4\xc3\x95',2004-07-30 18:00:00
1,2,253022876,1030,adventure-works\kevin0,6,Marketing Assistant,1977-06-03,S,M,1997-02-26,b'\x00',42,41,b'\x01',b'@\x02H\x1b\xc3\x80\xc2\x95\x0fA\xc2\xa7\x17\xc3\xab)',2004-07-30 18:00:00
2,21,277173473,1231,adventure-works\peter0,148,Production Control Manager,1972-12-04,M,M,1999-01-02,b'\x01',43,41,b'\x01',b'b\xc3\x91\xc3\x95i\x17\xc3\xa8\xc3\xa7E\xc2\x9d\xc3\xac',2005-01-26 02:17:08
3,25,360868122,1054,adventure-works\zheng0,21,Production Supervisor - WC10,1973-11-26,S,M,1999-01-04,b'\x00',66,53,b'\x01',"b""@'_\xc3\x87\xc3\xa3\xc2\xac\xc2\xbfN\xc2\x91\xc3\x85""",2004-07-30 18:00:00
4,26,964089218,1097,adventure-works\ivo0,108,Production Technician - WC20,1972-02-04,M,M,1999-01-05,b'\x00',9,24,b'\x01',b'\xc3\xb3&:\xc3\x98\xc2\xa7~{G\xc2\xa5\xc2\xbb~',2004-07-30 18:00:00
5,27,384162788,1156,adventure-works\paul0,87,Production Technician - WC40,1970-12-15,S,M,1999-01-05,b'\x00',68,54,b'\x01',"b""\xc2\x9e\x04\x17\x02f\x15\xc2\xb6B\xc2\x80'A\xc2\xb7""",2004-07-30 18:00:00
6,29,571658797,1199,adventure-works\kendall0,14,Production Technician - WC50,1976-06-30,M,M,1999-01-06,b'\x00',11,25,b'\x01',"b""'v e!U\xc2\x8eJ\xc2\xad<\xc2\xb2\xc3\xb1""",2004-07-30 18:00:00
7,31,761597760,1140,adventure-works\alejandro0,210,Production Technician - WC40,1979-01-06,S,M,1999-01-07,b'\x00',52,46,b'\x01',"b'\xc3\x92!s\xc2\x8cd,\x02I\xc2\x9dd\xc2\x8f\\'",2004-07-30 18:00:00
8,32,271438431,1122,adventure-works\garrett0,184,Production Technician - WC30,1974-09-26,S,M,1999-01-08,b'\x00',34,37,b'\x01',b'/\xc3\xb7\xc3\xb5\xc2\xa6\x03\xc2\xaa\xc2\xb7A\xc2\x8bn',2004-07-30 18:00:00
9,33,160739235,1124,adventure-works\jianshuo0,135,Production Technician - WC30,1973-08-27,S,M,1999-01-08,b'\x00',36,38,b'\x01',b'j\x13\xc3\xbfod\xc2\x96\xc2\xb9N\xc2\x92C\xc3\xba',2004-07-30 18:00:00
10,38,630184120,1065,adventure-works\jinghao0,21,Production Supervisor - WC50,1979-03-09,S,M,1999-01-09,b'\x00',77,58,b'\x01',b'\xc3\x93\x07\xc3\x8a+\xc2\xac\xc3\xb2\x06D\xc2\x90O\xc3',2004-07-30 18:00:00
11,39,545337468,1108,adventure-works\michael0,182,Production Technician - WC20,1974-12-19,S,M,1999-01-10,b'\x00',20,30,b'\x01',b'\xc2\x82\xc3\xbe\xc3\x96OZS\xc3\x91M\xc2\xbe\xc2\xb1',2004-07-30 18:00:00
12,40,713403643,1167,adventure-works\yvonne0,159,Production Technician - WC45,1979-05-17,M,F,1999-01-10,b'\x00',79,59,b'\x01',"b'\xc2\xbf\xc3\x9a\xc3\x86\xc2\x83}\xc3\xbd[O\xc2\xbb""'",2004-07-30 18:00:00
13,45,295971920,1135,adventure-works\fred0,210,Production Technician - WC40,1979-07-27,S,M,1999-01-13,b'\x00',47,43,b'\x01',b'\xc3\xa8\xc2\x8a5E\x0e\x0b\x11L\xc2\x90\xc2\xbb\xc3\x9a',2004-07-30 18:00:00
14,46,95958330,1033,adventure-works\sariya0,6,Marketing Specialist,1977-06-21,S,M,1999-01-13,b'\x00',45,42,b'\x01',b'\xc2\xb7\xc3\xb1!\xc2\xaf\xc2\x91\x06\xc2\xadH\xc2\xb3%',2004-07-30 18:00:00
15,50,351069889,1119,adventure-works\susan1,184,Production Technician - WC30,1973-05-03,S,F,1999-01-15,b'\x00',31,35,b'\x01',b'\xc3\x95u=\xc3\xb7{\xc2\xb4\xc3\xaeF\xc2\xad\x11{',2004-07-30 18:00:00
16,51,370989364,1060,adventure-works\reuben0,21,Production Supervisor - WC40,1977-09-27,M,M,1999-01-16,b'\x00',72,56,b'\x01',b'\xc2\xa6\xc3\xa2\xc3\xaeq\xc2\xb3\xc2\xb9\xc3\xb4K\xc2\x89',2004-07-30 18:00:00
17,52,275962311,1162,adventure-works\kirk0,123,Production Technician - WC45,1975-03-10,S,M,1999-01-16,b'\x00',74,57,b'\x01',b'\xc2\xaa[\xc3\x92\x08{\x16\xc2\x9cI\xc2\x8bQ1\xc3',2004-07-30 18:00:00
18,53,36151748,1221,adventure-works\david2,18,Production Technician - WC60,1975-01-30,M,M,1999-01-16,b'\x00',33,36,b'\x01',b'\xc2\xb8{a\xc3\xbc\xc2\xa3\xc3\x92tC\xc2\x87<\xc2',2004-07-30 18:00:00
19,56,918737118,1146,adventure-works\kevin1,210,Production Technician - WC40,1976-01-26,S,M,1999-01-18,b'\x00',58,49,b'\x01',"b""\xc3\xbf\xc2\x95~\xc3\x9c^'\xc3\x82A\xc2\x8e\xc3\x93""",2004-07-30 18:00:00
20,60,674171828,1189,adventure-works\jim0,74,Production Technician - WC50,1976-10-09,M,M,1999-01-20,b'\x00',1,20,b'\x01',b'n\xc2\x87ua\xc3\x8c\xc2\x8f\x17I\xc2\xbe\x06\xc3\xbc',2004-07-30 18:00:00
21,61,138280935,1130,adventure-works\carole0,173,Production Technician - WC30,1973-11-19,M,F,1999-01-20,b'\x00',42,41,b'\x01',b'\xc3\xb1Aj\xc3\x87\xc2\x90\xc2\xa3\xc3\xa4J\xc2\xa8*',2004-07-30 18:00:00
22,63,502058701,1157,adventure-works\gary0,87,Production Technician - WC40,1978-06-17,S,M,1999-01-23,b'\x00',69,54,b'\x01',b'R`=\xc2\xa0\xc2\x85\x1f\xc2\xbeN\xc2\xaa\xc3\x89\xc2',2004-07-30 18:00:00
23,64,7201901,1055,adventure-works\cristian0,21,Production Supervisor - WC10,1974-05-13,M,M,1999-01-23,b'\x00',67,53,b'\x01',b'\x16d\xc3\xa1[p\xc2\x85}A\xc2\x9eT\x04}\xc2',2004-07-30 18:00:00
24,66,525932996,1259,adventure-works\janaina0,42,Application Specialist,1975-03-03,M,F,1999-01-24,b'\x01',71,55,b'\x01',b'\xc3\x875\x15$1zjJ\xc2\x9e\r\xc2\xa8<0',2004-07-30 18:00:00
25,68,370487086,1141,adventure-works\shammi0,210,Production Technician - WC40,1970-11-05,M,M,1999-01-25,b'\x00',53,46,b'\x01',b'\xc2\x94\x0c\xc3\xaf\xc2\x9biy\x05I\xc2\x9aB\xc3\x8e',2004-07-30 18:00:00
26,69,54759846,1184,adventure-works\linda0,38,Production Technician - WC50,1977-08-17,M,F,1999-01-26,b'\x00',96,68,b'\x01',b'\xc2\x9cu\xc2\x84\xc3\xbb\xc2\x87\xc2\xb6\xc2\xb2C\xc2\x87',2004-07-30 18:00:00
27,70,619308550,1239,adventure-works\mindy0,30,Benefits Specialist,1974-12-22,M,F,1999-01-26,b'\x00',51,45,b'\x01',b'\xc2\xb6zM\xc2\x83\xc3\xa6\x06DI\xc2\xb4/\x02\xc2',2004-07-30 18:00:00
28,71,121491555,1243,adventure-works\wendy0,140,Finance Manager,1974-11-12,S,F,1999-01-26,b'\x01',55,47,b'\x01',b'\x08\x04A\xc2\x8f\xc2\xa8JgM\xc2\x88mS\x0b\xc3',2004-07-30 18:00:00
29,72,420776180,1286,adventure-works\kim0,85,Stocker,1974-06-01,S,F,1999-01-27,b'\x00',98,69,b'\x01',b'\xc2\x97\xc3\xb1Pa#y\xc3\x94@\xc2\x84\xc3\xb2\xc2',2004-07-30 18:00:00
30,74,778552911,1066,adventure-works\kok-ho0,21,Production Supervisor - WC50,1970-05-30,S,M,1999-01-28,b'\x00',78,59,b'\x01',"b'\x0f,\xc3\xbbW\x05\xc2\xb1\xc3\xb0I\xc2\x96z\xc2\x88'",2004-07-30 18:00:00
31,75,435234965,1168,adventure-works\douglas0,159,Production Technician - WC45,1975-12-26,M,M,1999-01-28,b'\x00',80,60,b'\x01',b'\xc3\xab\xc3\xad\xc2\xb0\x1aXu4G\xc2\x84#Z\x11',2004-07-30 18:00:00
32,76,339712426,1227,adventure-works\james0,7,Production Technician - WC60,1974-08-26,M,M,1999-01-28,b'\x00',39,39,b'\x01',b'Z-\xc3\xa5\xc2\x82[\x16mL\xc2\x97s\xc3\x83\xc2',2004-07-30 18:00:00
33,78,368920189,1109,adventure-works\nitin0,182,Production Technician - WC20,1977-01-01,S,M,1999-01-29,b'\x00',21,30,b'\x01',b'\xc2\x87g\xc2\xbc\xc3\xab-?kO\xc2\x9e\xc2\xa3M',2004-07-30 18:00:00
34,79,811994146,1050,adventure-works\diane1,158,Research and Development Engineer,1976-07-06,S,F,1999-01-30,b'\x01',62,51,b'\x01',b'5&\x111;f\x18@\xc2\xb4\xc2\xa2\xc2\xa6\xc2\x85',2004-07-30 18:00:00
35,82,264306399,1238,adventure-works\vidur0,30,Recruiter,1974-09-02,S,M,1999-02-02,b'\x00',50,45,b'\x01',b'Yk\xc3\xa7G7\xc2\xb1rE\xc2\xadUk>h',2004-07-30 18:00:00
36,84,693325305,1222,adventure-works\nancy0,7,Production Technician - WC60,1978-12-21,M,F,1999-02-03,b'\x00',34,37,b'\x01',b'\x06\xc2\xb3~k\x00\xc2\x9ajI\xc2\x98\xc2\xa9N\xc2',2004-07-30 18:00:00
37,86,746373306,1120,adventure-works\david3,184,Production Technician - WC30,1971-09-04,S,M,1999-02-03,b'\x00',32,36,b'\x01',"b'\xc3\x94X\xc3\x83\xc2\x84\xc2\x93$,E\xc2\xb7\xc3\x96'",2004-07-30 18:00:00
38,87,750905084,1061,adventure-works\david4,21,Production Supervisor - WC40,1973-08-02,S,M,1999-02-04,b'\x00',73,56,b'\x01',b'\xc3\xa88eQ[\x11\xc3\xb4D\xc2\xaa{\xc3\xa6\xc3',2004-07-30 18:00:00
39,88,514829225,1163,adventure-works\laura0,123,Production Technician - WC45,1971-01-26,S,F,1999-02-04,b'\x00',75,57,b'\x01',"b""\xc2\xbae\xc3\x8d\xc3\xbc\x02'\tD\xc2\xaeVu\xc2""",2004-07-30 18:00:00
40,89,750246141,1206,adventure-works\margie0,16,Production Technician - WC60,1976-06-20,M,F,1999-02-05,b'\x00',18,29,b'\x01',b'/n-5[e\xc2\xa2I\xc2\x9f\xc3\xac\xc3\xaf\xc3',2004-07-30 18:00:00
41,91,19312190,1137,adventure-works\lorraine0,210,Production Technician - WC40,1978-12-28,M,F,1999-02-05,b'\x00',49,44,b'\x01',b'\xc2\xb6f9\xc2\xa6\xc3\x96\xc2\x9a\xc2\xbc@\xc2\xaf\xc3',2004-07-30 18:00:00
42,92,212801092,1104,adventure-works\fadi0,143,Production Technician - WC20,1979-03-19,S,M,1999-02-05,b'\x00',16,28,b'\x01',b'o7#\xc2\x99\xc3\x90&EH\xc2\x9d\xc2\x99\xc3\x8c',2004-07-30 18:00:00
43,96,621209647,1233,adventure-works\william0,44,Scheduling Assistant,1971-12-08,M,M,1999-02-08,b'\x00',45,42,b'\x01',"b'b\xc3\x8dh\x1a\xc3\xa9o\x13F\xc2\x90\xc3\x94,\xc3'",2004-07-30 18:00:00
44,97,420023788,1131,adventure-works\bjorn0,173,Production Technician - WC30,1979-12-08,S,M,1999-02-08,b'\x00',43,41,b'\x01',b'\xc3\xa0\xc3\xa1B\xc2\xa9^-XH\xc2\x97\xc3\x80\xc2',2004-07-30 18:00:00
45,98,199546871,1174,adventure-works\scott0,197,Production Technician - WC45,1977-03-13,M,M,1999-02-09,b'\x00',86,63,b'\x01',b'\n\xc2\xa5]\xc3\xa3Q\xc2\xbb\x08N\xc2\x8b\xc2\x8d\xc2',2004-07-30 18:00:00
46,102,671089628,1260,adventure-works\dan0,42,Application Specialist,1971-07-28,M,M,1999-02-12,b'\x01',72,56,b'\x01',b'\x10\xc3\x90\xc2\xb0q\xc3\x85Z\xc2\x91N\xc2\x8e\xc3\xba',2004-07-30 18:00:00
47,105,992874797,1142,adventure-works\paula1,210,Production Technician - WC40,1977-03-13,M,F,1999-02-13,b'\x00',54,47,b'\x01',b'F\xc2\xbe\xc3\x92]O \xc3\xb3J\xc2\x91\xc3\xb5^',2004-07-30 18:00:00
48,108,45615666,1228,adventure-works\eric0,21,Production Supervisor - WC20,1975-02-20,M,M,1999-02-15,b'\x00',40,40,b'\x01',b'\xc2\x9b\xc3\xb3\xc2\xbc*\xc3\x97\xc2\x88\xc3\xbaI\xc2\x82',2004-07-30 18:00:00
49,110,733022683,1126,adventure-works\jason0,135,Production Technician - WC30,1979-01-08,S,M,1999-02-15,b'\x00',38,39,b'\x01',b'\x1dPl\xc3\x81-\xc2\x94\xc2\xb0N\xc2\xb5\xc3\x84\xc3',2004-07-30 18:00:00
50,111,381772114,1271,adventure-works\mark0,41,Quality Assurance Technician,1976-05-31,S,M,1999-02-16,b'\x00',83,61,b'\x01',"b""'\xc3\xafckU,LO\xc2\xbe)\xc3\xbc\xc3\xa8""",2004-07-30 18:00:00
51,113,364818297,1110,adventure-works\marc0,184,Production Technician - WC30,1976-11-24,M,M,1999-02-17,b'\x00',22,31,b'\x01',b'\xc2\xbc\x1a\x15\x1fJ\xc3\x9b\x1aC\xc2\x8a]\x15\xc3\xb4',2004-07-30 18:00:00
52,116,749211824,1144,adventure-works\frank0,210,Production Technician - WC40,1977-10-07,M,M,1999-02-18,b'\x00',56,48,b'\x01',b'x\xc3\x92\xc2\x9a\xc3\x9d\x17\xc3\xad\xc3\x8f@\xc2\x86\x19',2004-07-30 18:00:00
53,118,92096924,1196,adventure-works\diane2,14,Production Technician - WC50,1979-09-10,S,F,1999-02-19,b'\x00',8,24,b'\x01',b'!)\x1ar\x15\xc3\x84\xc3\x9eF\xc2\x91\x11\x13\xc3\xb2',2004-07-30 18:00:00
54,124,87268837,1121,adventure-works\eugene0,184,Production Technician - WC30,1977-08-15,S,M,1999-02-22,b'\x00',33,36,b'\x01',b't\xc3\x93\xc2\xa1\x1b\xc2\xae\x18\xc3\xadH\xc2\x93\xc2\x8f',2004-07-30 18:00:00
55,126,539490372,1164,adventure-works\chris0,123,Production Technician - WC45,1979-01-17,M,M,1999-02-23,b'\x00',76,58,b'\x01',b'\xc3\xb3#\x020\xc2\x87U0B\xc2\x90\xc2\x9b\xc3\x99',2004-07-30 18:00:00
56,127,242381745,1266,adventure-works\sean1,90,Document Control Assistant,1977-04-12,S,M,1999-02-23,b'\x00',78,59,b'\x01',b'\xc2\xa9W\xc2\x86\xc3\xb7\xc3\xaf\xc2\x83MK\xc2\x98\t',2004-07-30 18:00:00
57,130,931190412,1250,adventure-works\bryan1,139,Accounts Receivable Specialist,1974-10-22,S,M,1999-02-25,b'\x00',62,51,b'\x01',b'\xc3\xacq>\xc3\x8b\xc2\x81\xc2\xa3\x16G\xc2\x87\xc3\x9f',2004-07-30 18:00:00
58,132,981495526,1234,adventure-works\sairaj0,44,Scheduling Assistant,1978-01-22,M,M,1999-02-27,b'\x00',46,43,b'\x01',b' \xc2\xa76M2\xc3\x8eGL\xc2\x86j\xc3\x9bx',2004-07-30 18:00:00
59,133,363996959,1132,adventure-works\michiko0,173,Production Technician - WC30,1972-07-28,S,M,1999-02-27,b'\x00',44,42,b'\x01',b'\xc2\xb6\xc3\xb5Y\xc3\xb3\x18^bL\xc2\x851\x14\xc3',2004-07-30 18:00:00
60,134,585408256,1116,adventure-works\benjamin0,184,Production Technician - WC30,1976-02-06,S,M,1999-02-28,b'\x00',28,34,b'\x01',b'$\xc3\xb8\xc2\xa6\xc3\xb1[\xc2\x89\x0fJ\xc2\xaf\x1b\x05',2004-07-30 18:00:00
61,135,386315192,1057,adventure-works\cynthia0,21,Production Supervisor - WC30,1971-09-19,S,F,1999-02-28,b'\x00',69,54,b'\x01',b'F\xc3\x9c\xc3\xa1\xc3\xb9\x03\r\xc2\x8aJ\xc2\xb6\xc2\x93',2004-07-30 18:00:00
62,137,410742000,1202,adventure-works\britta0,16,Production Technician - WC60,1979-10-30,M,F,1999-03-02,b'\x00',14,27,b'\x01',b'\x7fg\x12\xc3\xbc\xc3\xb8B\xc2\x90G\xc2\xadihP',2004-07-30 18:00:00
63,139,30845,1245,adventure-works\david6,140,Accounts Manager,1973-08-08,M,M,1999-03-03,b'\x01',57,48,b'\x01',b'4\xc3\x95\xc3\x89-\xc3\x91\xc3\xb5\x14J\xc2\x82\xc2\x82',2004-07-30 18:00:00
64,142,764853868,1127,adventure-works\andy0,135,Production Technician - WC30,1973-11-20,M,M,1999-03-04,b'\x00',39,39,b'\x01',b'\xc3\xbekZaF07@\xc2\x97d#\xc2\x855',2004-07-30 18:00:00
65,144,456839592,1170,adventure-works\robert0,159,Production Technician - WC45,1975-04-01,S,M,1999-03-06,b'\x00',82,61,b'\x01',"b'N\x15\x03""\xc2\xbd^\xc3\x8aJ\xc2\x99\xc2\xbe\xc3\x98'",2004-07-30 18:00:00
66,145,131471224,1272,adventure-works\andreas0,41,Quality Assurance Technician,1979-04-29,M,M,1999-03-06,b'\x00',84,62,b'\x01',b'O\xc3\x96\xc3\x9d\xc3\xb4\xc3\xbe\xc3\x9f\xc3\xb3M\xc2\xaa',2004-07-30 18:00:00
67,146,259388196,1111,adventure-works\reed0,184,Production Technician - WC30,1979-02-09,M,M,1999-03-06,b'\x00',23,31,b'\x01',b'\x00|\xc2\x96\xc2\xb3\x14p`I\xc2\xaf\x15\xc2\xb1\xc2',2004-07-30 18:00:00
68,148,519899904,1052,adventure-works\james1,109,Vice President of Production,1973-02-07,S,M,1999-03-07,b'\x01',64,52,b'\x01',b'$O1\xc3\x97\xc3\xb1*\xc2\x9cB\xc2\x9b\xc2\xbb@',2004-07-30 18:00:00
69,149,314747499,1261,adventure-works\ramesh0,42,Application Specialist,1978-04-14,S,M,1999-03-07,b'\x01',73,56,b'\x01',b'i\x02\x19\xc2\xbe\x03@\x7fM\xc2\x80\xc2\x9e{?\xc3',2004-07-30 18:00:00
70,150,858323870,1256,adventure-works\stephanie0,42,Network Manager,1974-04-26,S,F,1999-03-08,b'\x01',68,54,b'\x01',"b'{\xc2\xbb\x1c""\xc2\xae\xc2\x8b+E\xc2\xa1o\xc2\xa6'",2004-07-30 18:00:00
71,151,25011600,1095,adventure-works\samantha0,108,Production Technician - WC20,1977-12-23,M,F,1999-03-08,b'\x00',7,23,b'\x01',b'\xc3\x9d\xc3\xad)\x16\xc2\xae\xc3\x90\xc2\xb9L\xc2\xa5\xc2',2004-07-30 18:00:00
72,152,436757988,1138,adventure-works\tawana0,210,Production Technician - WC40,1979-12-12,S,M,1999-03-09,b'\x00',50,45,b'\x01',b'P>J\xc2\xbb.#\x12B\xc2\x9f\xc2\xaf\xc3\xa6t',2004-07-30 18:00:00
73,153,652535724,1197,adventure-works\denise0,14,Production Technician - WC50,1978-08-07,M,F,1999-03-09,b'\x00',9,24,b'\x01',b'C\xc2\x8c\xc2\x87wn\xc3\xb1}C\xc2\x89/<\xc3',2004-07-30 18:00:00
74,158,134969118,1049,adventure-works\dylan0,3,Research and Development Manager,1977-03-27,M,M,1999-03-12,b'\x01',61,50,b'\x01',b'\xc3\x8a\xc3\x9eFO\x01\xc3\xaf\xc3\xbdA\xc2\x98)\n',2004-07-30 18:00:00
75,160,305522471,1106,adventure-works\john2,182,Production Technician - WC20,1976-05-06,M,M,1999-03-13,b'\x00',18,29,b'\x01',b'Q\xc2\x99\xc2\xb6\xc2\xba\xc2\xad(\xc3\x8aK\xc2\xb5\xc2',2004-07-30 18:00:00
76,162,788456780,1208,adventure-works\jose0,16,Production Technician - WC60,1974-09-01,M,M,1999-03-14,b'\x00',20,30,b'\x01',b'V%\xc2\x91\xc2\x9e\xc2\xba\xc2\x88\xc3\xaeA\xc2\xb9F',2004-07-30 18:00:00
77,163,370581729,1188,adventure-works\mandar0,74,Production Technician - WC50,1976-04-21,S,M,1999-03-14,b'\x00',0,20,b'\x01',b'\xc2\x8a\x06\x0e\x1f\xc3\x85H\xc2\xbf@\xc2\x81\xc2\x90V',2004-07-30 18:00:00
78,164,603686790,1047,adventure-works\mikael0,274,Buyer,1974-09-18,S,M,1999-03-14,b'\x00',59,49,b'\x01',b'\xc3\xbfU\xc3\xbd\xc3\x90\xc3\xbaB\x1eI\xc2\x8b;\xc2',2004-07-30 18:00:00
79,167,227319668,1133,adventure-works\carol0,173,Production Technician - WC30,1978-11-18,M,F,1999-03-16,b'\x00',45,42,b'\x01',b'\xc2\xa3\xc2\x82\x01\xc2\x8dY[\xc3\xaaN\xc2\x9b<\xc3',2004-07-30 18:00:00
80,170,470689086,1235,adventure-works\alan0,44,Scheduling Assistant,1974-04-30,M,M,1999-03-17,b'\x00',47,43,b'\x01',b'T\x182\xc3\x9ev\xc2\xb0YM\xc2\xbb{B\x15 ',2004-07-30 18:00:00
81,171,860123571,1117,adventure-works\david7,184,Production Technician - WC30,1975-10-25,M,M,1999-03-18,b'\x00',29,34,b'\x01',b'\xc2\x89\xc2\xb6\xc2\xaf\xc2\x85\xc2\xab~\xc2\xa8A\xc2\xb1',2004-07-30 18:00:00
82,173,578935259,1058,adventure-works\michael3,21,Production Supervisor - WC30,1979-03-02,S,M,1999-03-19,b'\x00',70,55,b'\x01',b'\xc3\x97r\xc3\x97\x1aJ{{J\xc2\x86vI\xc3\x9d',2004-07-30 18:00:00
83,175,754372876,1203,adventure-works\suchitra0,16,Production Technician - WC60,1977-07-11,M,F,1999-03-20,b'\x00',15,27,b'\x01',b'2\xc3\x99\xc3\x9bj\xc2\xa5\r\\O\xc2\xafg\xc2\x8e',2004-07-30 18:00:00
84,177,404159499,1101,adventure-works\terrence0,143,Production Technician - WC20,1975-01-09,S,M,1999-03-20,b'\x00',13,26,b'\x01',b'Bd\xc2\xa7M\xc3\xaf^\xc3\xbbA\xc2\xae\x19\x16\xc3',2004-07-30 18:00:00
85,182,862951447,1230,adventure-works\katie0,21,Production Supervisor - WC20,1974-12-20,S,F,1999-03-24,b'\x00',42,41,b'\x01',b'\x11\xc2\xb2\xc3\xa8[\xc3\xa5\xc3\x8b\xc3\x98E\xc2\x84\xc3',2004-07-30 18:00:00
86,183,551346974,1112,adventure-works\russell1,184,Production Technician - WC30,1972-03-14,M,M,1999-03-25,b'\x00',24,32,b'\x01',b'\xc2\x89yL\xc3\x95u&\xc3\xb3N\xc2\xb3\xc2\x927',2004-07-30 18:00:00
87,184,60114406,1056,adventure-works\jack0,21,Production Supervisor - WC30,1973-07-23,S,M,1999-03-25,b'\x00',68,54,b'\x01',b'0r\xc2\xa4i\xc3\xaep\xc3\xbdH\xc2\xac\x15\xc3\x83',2004-07-30 18:00:00
88,185,33237992,1053,adventure-works\andrew0,21,Production Supervisor - WC10,1978-10-08,S,M,1999-03-26,b'\x00',65,52,b'\x01',b'\x05[6\x08C\xc3\x81`B\xc2\xa9<kiA\xc2',2004-07-30 18:00:00
89,186,1300049,1155,adventure-works\nicole0,87,Production Technician - WC40,1976-05-10,M,F,1999-03-26,b'\x00',67,53,b'\x01',b';\x1eg\x15o\x01\xc3\xbdA\xc2\x84\x0bZ\xc2\x9f}',2004-07-30 18:00:00
90,188,672243793,1257,adventure-works\peter1,150,Network Administrator,1970-06-29,S,M,1999-03-27,b'\x00',69,54,b'\x01',b'j\x1e`\xc2\x86Ui\xc3\xbc@\xc2\xbbJ\x10S\xc2',2004-07-30 18:00:00
91,190,693168613,1139,adventure-works\ken1,210,Production Technician - WC40,1971-06-29,M,M,1999-03-28,b'\x00',51,45,b'\x01',b'\xc3\x98\x00\xc2\x9ci\xc2\xab\xc3\x84\xc3\x92L\xc2\xa4\xc2',2004-07-30 18:00:00
92,192,334834274,1182,adventure-works\michael4,38,Production Technician - WC50,1979-07-17,S,M,1999-03-29,b'\x00',94,67,b'\x01',"b""&\xc3\x80'\xc3\xabp\xc2\x94PD\xc2\x8d^\x1f8""",2004-07-30 18:00:00
93,193,399658727,1166,adventure-works\lionel0,159,Production Technician - WC45,1978-04-15,S,M,1999-03-30,b'\x00',78,59,b'\x01',b'\xc2\x98\x17\x1b#{\xc3\xb6\xc3\x81E\xc2\x96\xc2\x88&',2004-07-30 18:00:00
94,194,500412746,1225,adventure-works\thomas0,7,Production Technician - WC60,1976-02-11,M,M,1999-03-30,b'\x00',37,38,b'\x01',b'g\xc2\xaf\xc3\xb3\xc2\x8f\xc3\xb22\x08J\xc2\x98\xc3\x83',2004-07-30 18:00:00
95,195,652779496,1284,adventure-works\jimmy0,85,Stocker,1975-06-05,M,M,1999-03-30,b'\x00',96,68,b'\x01',"b""\xc2\x87'D\xc2\x96 \xc2\x95UI\xc2\xa4W8\xc2""",2004-07-30 18:00:00
96,196,878395493,1123,adventure-works\michael5,135,Production Technician - WC30,1972-10-19,M,M,1999-03-30,b'\x00',35,37,b'\x01',b'\xc3\x94v\x08+\xc2\x96\xc2\x89qN\xc2\xa6\x13\xc2\xbe',2004-07-30 18:00:00
97,197,332349500,1064,adventure-works\lori0,21,Production Supervisor - WC45,1970-08-19,S,F,1999-03-30,b'\x00',76,58,b'\x01',b'\xc3\xbc6\xc3\x94#\xc3\xb7\x08\xc2\x88I\xc2\x8bMI',2004-07-30 18:00:00
98,203,243322160,1032,adventure-works\terry0,6,Marketing Specialist,1976-03-07,M,M,1999-04-03,b'\x00',44,42,b'\x01',b'&v\r\xc2\xad\x06E\xc3\x84E\xc2\x89\xc2\x8f\xc2\x9d',2004-07-30 18:00:00
99,204,568626529,1115,adventure-works\john3,184,Production Technician - WC30,1972-04-24,S,M,1999-04-04,b'\x00',27,33,b'\x01',b'\xc2\xb1\xc3\xaa\xc3\x87\xc2\x96\xc3\xaamYL\xc2\xaf\xc3',2004-07-30 18:00:00