In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option ('display.max_columns',None)

In [3]:
from pydataset import data 
mtcars= data ('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
','.join(data()['dataset_id'])

'AirPassengers,BJsales,BOD,Formaldehyde,HairEyeColor,InsectSprays,JohnsonJohnson,LakeHuron,LifeCycleSavings,Nile,OrchardSprays,PlantGrowth,Puromycin,Titanic,ToothGrowth,UCBAdmissions,UKDriverDeaths,UKgas,USAccDeaths,USArrests,USJudgeRatings,USPersonalExpenditure,VADeaths,WWWusage,WorldPhones,airmiles,airquality,anscombe,attenu,attitude,austres,cars,chickwts,co2,crimtab,discoveries,esoph,euro,faithful,freeny,infert,iris,islands,lh,longley,lynx,morley,mtcars,nhtemp,nottem,npk,occupationalStatus,precip,presidents,pressure,quakes,randu,rivers,rock,sleep,stackloss,sunspot.month,sunspot.year,sunspots,swiss,treering,trees,uspop,volcano,warpbreaks,women,acme,aids,aircondit,aircondit7,amis,aml,bigcity,brambles,breslow,calcium,cane,capability,catsM,cav,cd4,channing,city,claridge,cloth,co.transfer,coal,darwin,dogs,downs.bc,ducks,fir,frets,grav,gravity,hirose,islay,manaus,melanoma,motor,neuro,nitrofen,nodal,nuclear,paulsen,poisons,polar,remission,salinity,survival,tau,tuna,urine,wool,aids,alloauto,allograft,azt,baboon,bcdeter,bfeed,bmt,bnct,btrial,burn,channing,drug6mp,drughiv,hodg,kidney,kidrecurr,kidtran,larynx,lung,pneumon,psych,rats,std,stddiag,tongue,twins,Animals2,CrohnD,NOxEmissions,SiegelsEx,aircraft,airmay,alcohol,ambientNOxCH,bushfire,carrots,cloud,coleman,condroz,cushny,delivery,education,epilepsy,exAM,foodstamp,hbk,heart,kootenay,lactic,milk,pension,phosphor,pilot,possumDiv,pulpfiber,radarImage,salinity,starsCYG,telef,toxicity,vaso,wagnerGrowth,wood,AMSsurvey,Adler,Angell,Anscombe,Baumann,Bfox,Blackmoor,Burt,CanPop,Chile,Chirot,Cowles,Davis,DavisThin,Depredations,Duncan,Ericksen,Florida,Freedman,Friendly,Ginzberg,Greene,Guyer,Hartnagel,Highway1,Leinhardt,Mandel,Migration,Moore,Mroz,OBrienKaiser,Ornstein,Pottery,Prestige,Quartet,Robey,SLID,Sahlins,Salaries,Soils,States,Transact,UN,USPop,Vocab,WeightLoss,Womenlf,Wool,agriculture,animals,chorSub,flower,plantTraits,pluton,ruspini,votes.repub,xclara,affairs,azcabgptca,azdrg112,azpro,azprocedure,badhealth,fasttrakg,fishing,lbw,lbwgrp,loomis,mdvis,medpar,nuts,rwm,rwm1984,rwm5yr,ships,smoking,titanic,titanicgrp,Accident,Airline,Airq,Benefits,Bids,BudgetFood,BudgetItaly,BudgetUK,Bwages,CPSch3,CRANpackages,Capm,Car,Caschool,Catsup,Cigar,Cigarette,Clothing,Computers,Cracker,Crime,DM,Diamond,Doctor,DoctorAUS,DoctorContacts,Earnings,Electricity,Fair,Fatality,Fishing,Forward,FriendFoe,Garch,Gasoline,Griliches,Grunfeld,HC,HI,Hdma,Heating,Hedonic,Housing,Icecream,Journals,Kakadu,Ketchup,Klein,LaborSupply,Labour,MCAS,Males,Mathlevel,MedExp,Metal,Mode,ModeChoice,Mofa,Mroz,MunExp,NaturalPark,Nerlove,OFP,Oil,PSID,Participation,PatentsHGH,PatentsRD,Pound,Produc,RetSchool,SP500,Schooling,Somerville,Star,Strike,StrikeDur,StrikeNb,SumHes,Tobacco,Train,TranspEq,Treatment,Tuna,USFinanceIndustry,USclassifiedDocuments,USstateAbbreviations,UStaxWords,UnempDur,Unemployment,University,VietNamH,VietNamI,Wages,Wages1,Workinghours,Yen,Yogurt,bankingCrises,incomeInequality,nonEnglishNames,politicalKnowledge,PD,aldh2,apoeapoc,cf,crohn,fa,fsnps,hla,hr1420,l51,lukas,mao,mfblong,mhtdata,nep499,diamonds,economics,midwest,movies,mpg,msleep,presidential,seals,Arbuthnot,Bowley,Cavendish,ChestSizes,CushnyPeebles,CushnyPeeblesN,Dactyl,DrinksWages,Fingerprints,Galton,GaltonFamilies,Guerry,Jevons,Langren.all,Langren1644,Macdonell,MacdonellDF,Michelson,MichelsonSets,Minard.cities,Minard.temp,Minard.troops,Nightingale,OldMaps,PearsonLee,PolioTrials,Prostitutes,Pyx,Quarrels,Snow.deaths,Snow.polygons,Snow.pumps,Snow.streets,Wheat,Wheat.monarchs,Yeast,YeastD.mat,ZeaMays,barley,environmental,ethanol,melanoma,singer,Aids2,Animals,Boston,Cars93,Cushings,DDT,GAGurine,Insurance,Melanoma,OME,Pima.te,Pima.tr,Pima.tr2,Rabbit,Rubber,SP500,Sitka,Sitka89,Skye,Traffic,UScereal,UScrime,VA,abbey,accdeaths,anorexia,bacteria,beav1,beav2,biopsy,birthwt,cabbages,caith,cats,cement,chem,coop,cpus,crabs,deaths,drivers,eagles,epil,farms,fgl,forbes,galaxies,gehan,genotype,geyser,gilgais,hills,housing,immer,leuk,mammals,mcycle,menarche,michelson,minn38,motors,muscle,newcomb,nlschools,npk,npr1,oats,painters,petrol,quine,road,rotifer,ships,shrimp,shuttle,snails,steam,stormer,survey,synth.te,synth.tr,topo,waders,whiteside,wtloss,Cigar,Crime,EmplUK,Gasoline,Grunfeld,Hedonic,LaborSupply,Males,Produc,Snmesp,SumHes,Wages,baseball,AustralianElectionPolling,AustralianElections,EfronMorris,RockTheVote,UKHouseOfCommons,absentee,admit,bioChemists,ca2006,iraqVote,politicalInformation,presidentialElections,prussian,unionDensity,vote92,french_fries,smiths,tips,car.test.frame,car90,cu.summary,kyphosis,solder,stagec,PublicSchools,Bollen,CNES,Klein,Kmenta,Tests,bladder,cancer,cgd,colon,flchain,heart,kidney,leukemia,logan,lung,mgus,nwtco,ovarian,pbc,rats,stanford2,tobin,veteran,Arthritis,Baseball,BrokenMarriage,Bundesliga,Bundestag2005,Butterfly,CoalMiners,DanishWelfare,Employment,Federalist,Hitters,HorseKicks,Hospital,JobSatisfaction,JointSports,Lifeboats,NonResponse,OvaryCancer,PreSex,Punishment,RepVict,Saxony,SexualFun,SpaceShuttle,Suicide,Trucks,UKSoccer,VisualAcuity,VonBort,WeldonDice,WomenQueue,MatchIt.url,PErisk,SupremeCourt,Weimar,Zelig.url,approval,bivariate,coalition,coalition2,eidat,free1,free2,friendship,grunfeld,hoff,homerun,immi1,immi2,immi3,immi4,immi5,immigration,klein,kmenta,macro,mexico,mid,newpainters,sanction,sna.ex,swiss,tobin,turnout,voteincome,BCG,BtheB,CYGOB1,Forbes2000,GHQ,Lanza,agefat,aspirin,birthdeathrates,bladdercancer,clouds,epilepsy,foster,heptathlon,mastectomy,meteo,orallesions,phosphate,pistonrings,planets,plasma,polyps,polyps3,pottery,rearrests,respiratory,roomwidth,schizophrenia,schizophrenia2,schooldays,skulls,smoking,students,suicides,toothpaste,voting,water,watervoles,waves,weightgain,womensrole,Bechtoldt,Bechtoldt.1,Bechtoldt.2,Dwyer,Gleser,Gorsuch,Harman.5,Harman.8,Harman.political,Holzinger,Holzinger.9,Reise,Schmid,Thurstone,Thurstone.33,Tucker,ability,affect,bfi,bfi.dictionary,blot,burt,cities,cubits,cushny,epi,epi.bfi,epi.dictionary,galton,heights,income,iqitems,msq,neo,peas,sat.act,withinBetween,Bosco,CobarOre,Mammals,barro,engel,uis,dietox,koch,ohio,respdis,respiratory,seizure,sitka89,spruce,liver,portpirie,rain,summer,wavesurge,winter,arthritis,housing,bmw,danish,nidd.annual,nidd.thresh,siemens,sp.raw,spto87,Dyestuff,Dyestuff2,InstEval,Pastes,Penicillin,VerbAgg,cake,cbpp,grouseticks,sleepstudy'

In [5]:
mtcars.sample(3)

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Fiat 128        32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2

In [6]:
data('iris').head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [7]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [8]:
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [9]:
mtcars= data('mtcars')
mtcars= mtcars.astype({'cyl':'category','vs':'category','carb':'category','am':'category','gear':'category'})

In [10]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [11]:
mtcars.head()

                    mpg cyl   disp   hp  drat     wt   qsec vs am gear carb
Mazda RX4          21.0   6  160.0  110  3.90  2.620  16.46  0  1    4    4
Mazda RX4 Wag      21.0   6  160.0  110  3.90  2.875  17.02  0  1    4    4
Datsun 710         22.8   4  108.0   93  3.85  2.320  18.61  1  1    4    1
Hornet 4 Drive     21.4   6  258.0  110  3.08  3.215  19.44  1  0    3    1
Hornet Sportabout  18.7   8  360.0  175  3.15  3.440  17.02  0  0    3    2

In [12]:
mtcars.describe(include='all')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.0,32.000000,32.000000,32.000000,32.000000,32.000000,32.0,32.0,32.0,32.0
unique,NaN,3.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,6.0
top,NaN,8.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3.0,2.0
freq,NaN,14.0,NaN,NaN,NaN,NaN,NaN,18.0,19.0,15.0,10.0
mean,20.090625,NaN,230.721875,146.687500,3.596563,3.217250,17.848750,NaN,NaN,NaN,NaN
std,6.026948,NaN,123.938694,68.562868,0.534679,0.978457,1.786943,NaN,NaN,NaN,NaN
min,10.400000,NaN,71.100000,52.000000,2.760000,1.513000,14.500000,NaN,NaN,NaN,NaN
25%,15.425000,NaN,120.825000,96.500000,3.080000,2.581250,16.892500,NaN,NaN,NaN,NaN
50%,19.200000,NaN,196.300000,123.000000,3.695000,3.325000,17.710000,NaN,NaN,NaN,NaN
75%,22.800000,NaN,326.000000,180.000000,3.920000,3.610000,18.900000,NaN,NaN,NaN,NaN
max,33.900000,NaN,472.000000,335.000000,4.930000,5.424000,22.900000,NaN,NaN,NaN,NaN

In [13]:
mtcars['am']=mtcars['am'].map({0:'auto',1:'manual'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [14]:
mtcars['mpg'].max()

33.9

In [15]:
mtcars[mtcars['mpg']>30].sort_values('mpg',ascending=False)

                 mpg cyl  disp   hp  drat     wt   qsec vs      am gear carb
Toyota Corolla  33.9   4  71.1   65  4.22  1.835  19.90  1  manual    4    1
Fiat 128        32.4   4  78.7   66  4.08  2.200  19.47  1  manual    4    1
Honda Civic     30.4   4  75.7   52  4.93  1.615  18.52  1  manual    4    2
Lotus Europa    30.4   4  95.1  113  3.77  1.513  16.90  1  manual    5    2

In [16]:
mtcars[mtcars['mpg']== mtcars['mpg'].max()]

                 mpg cyl  disp  hp  drat     wt  qsec vs      am gear carb
Toyota Corolla  33.9   4  71.1  65  4.22  1.835  19.9  1  manual    4    1

In [17]:
mtcars[mtcars['mpg']<=mtcars['mpg'].mean()]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,auto,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,auto,3,4
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,auto,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,auto,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,auto,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,auto,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,auto,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,auto,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,auto,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,auto,3,4
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,auto,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,auto,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,auto,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,auto,3,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,manual,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,manual,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,manual,5,8

In [18]:
mtcars['cyl'].unique()

[6, 4, 8]
Categories (3, int64): [4, 6, 8]

In [19]:
mtcars['mpg'].unique()

array([21. , 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 19.2, 17.8, 16.4, 17.3,
       15.2, 10.4, 14.7, 32.4, 30.4, 33.9, 21.5, 15.5, 13.3, 27.3, 26. ,
       15.8, 19.7, 15. ])

In [20]:
mtcars['hp'].unique()

array([110,  93, 175, 105, 245,  62,  95, 123, 180, 205, 215, 230,  66,
        52,  65,  97, 150,  91, 113, 264, 335, 109])

In [21]:
df=mtcars.groupby (['cyl','am']) ['hp'].mean().reset_index(name='avg')
df

C:\Users\rajia\AppData\Local\Temp\ipykernel_15604\3133682589.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df=mtcars.groupby (['cyl','am']) ['hp'].mean().reset_index(name='avg')

  cyl      am         avg
0   4    auto   84.666667
1   4  manual   81.875000
2   6    auto  115.250000
3   6  manual  131.666667
4   8    auto  194.166667
5   8  manual  299.500000

In [22]:
df.rename(columns={'avg': 'avg_hp'})

  cyl      am      avg_hp
0   4    auto   84.666667
1   4  manual   81.875000
2   6    auto  115.250000
3   6  manual  131.666667
4   8    auto  194.166667
5   8  manual  299.500000

In [23]:
df.rename(columns={'avg_hp': 'avg'})

  cyl      am         avg
0   4    auto   84.666667
1   4  manual   81.875000
2   6    auto  115.250000
3   6  manual  131.666667
4   8    auto  194.166667
5   8  manual  299.500000

In [24]:
bins= [0,17,29,mtcars['mpg'].max()]
labels=['low','medium','high']
mtcars['mpg_label']=pd.cut(mtcars['mpg'],bins= bins, labels= labels, include_lowest= True)

In [25]:
mtcars.describe()

             mpg        disp          hp       drat         wt       qsec
count  32.000000   32.000000   32.000000  32.000000  32.000000  32.000000
mean   20.090625  230.721875  146.687500   3.596563   3.217250  17.848750
std     6.026948  123.938694   68.562868   0.534679   0.978457   1.786943
min    10.400000   71.100000   52.000000   2.760000   1.513000  14.500000
25%    15.425000  120.825000   96.500000   3.080000   2.581250  16.892500
50%    19.200000  196.300000  123.000000   3.695000   3.325000  17.710000
75%    22.800000  326.000000  180.000000   3.920000   3.610000  18.900000
max    33.900000  472.000000  335.000000   4.930000   5.424000  22.900000

In [26]:
bins=[0,70,150,250,mtcars['hp'].max()]
labels=['low','medium','high','veryhigh']
mtcars['hp_label']=pd.cut(mtcars['hp'],bins= bins, labels= labels, include_lowest= True)

In [27]:
mtcars['hp_label']. value_counts()

hp_label
medium      14
high        11
low          5
veryhigh     2
Name: count, dtype: int64

In [28]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4,medium,medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4,medium,medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1,medium,medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1,medium,medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2,medium,high

In [29]:
mtcars.groupby('mpg_label')['mpg'].count()

C:\Users\rajia\AppData\Local\Temp\ipykernel_15604\4268704863.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mtcars.groupby('mpg_label')['mpg'].count()

mpg_label
low       11
medium    17
high       4
Name: mpg, dtype: int64

In [30]:
mtcars.mpg_label.value_counts ()

mpg_label
medium    17
low       11
high       4
Name: count, dtype: int64

In [31]:
mtcars['vs'] = mtcars['vs'].map({0: 'Vshaped', 1:'Straight'})
mtcars ['vs'].head()

Mazda RX4             Vshaped
Mazda RX4 Wag         Vshaped
Datsun 710           Straight
Hornet 4 Drive       Straight
Hornet Sportabout     Vshaped
Name: vs, dtype: category
Categories (2, object): ['Vshaped', 'Straight']

In [32]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high

In [33]:
mtcars['car_name']= mtcars.index

In [34]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout

In [35]:
mtcars.dtypes

mpg           float64
cyl          category
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs           category
am           category
gear         category
carb         category
mpg_label    category
hp_label     category
car_name       object
dtype: object

In [36]:
print(len(mtcars[mtcars['mpg']>25]))
mtcars[mtcars['mpg']>25]

6

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,medium,medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa

In [37]:
mtcars[mtcars['mpg_label']== 'high']

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa

In [38]:
mtcars[mtcars['hp_label'] == 'high']

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino

In [39]:
mtcars[mtcars['wt'] >= 5]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial

In [40]:
mtcars.query('mpg <23')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,medium,medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,medium,medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,medium,medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,medium,medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,medium,medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,low,medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,low,medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,medium,medium,Volvo 142E

In [41]:
mtcars[mtcars['mpg'] <23] # we can write it down in both way with .query or like that both will show the same result
# query is a method used to filter rows using a condition as a string

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,medium,medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,medium,medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,medium,medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,medium,medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,medium,medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,low,medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,low,medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,medium,medium,Volvo 142E

In [42]:
mtcars.query('hp >150')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora

In [43]:
mtcars.query('mpg < 15 and hp >200')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28

In [44]:
mtcars.filter (items=['hp','mpg'])

                      hp   mpg
Mazda RX4            110  21.0
Mazda RX4 Wag        110  21.0
Datsun 710            93  22.8
Hornet 4 Drive       110  21.4
Hornet Sportabout    175  18.7
Valiant              105  18.1
Duster 360           245  14.3
Merc 240D             62  24.4
Merc 230              95  22.8
Merc 280             123  19.2
Merc 280C            123  17.8
Merc 450SE           180  16.4
Merc 450SL           180  17.3
Merc 450SLC          180  15.2
Cadillac Fleetwood   205  10.4
Lincoln Continental  215  10.4
Chrysler Imperial    230  14.7
Fiat 128              66  32.4
Honda Civic           52  30.4
Toyota Corolla        65  33.9
Toyota Corona         97  21.5
Dodge Challenger     150  15.5
AMC Javelin          150  15.2
Camaro Z28           245  13.3
Pontiac Firebird     175  19.2
Fiat X1-9             66  27.3
Porsche 914-2         91  26.0
Lotus Europa         113  30.4
Ford Pantera L       264  15.8
Ferrari Dino         175  19.7
Maserati Bora        335  15.0
Volvo 142E           109  21.4

In [45]:
mtcars.filter(items= ['am','vs'])

                         am        vs
Mazda RX4            manual   Vshaped
Mazda RX4 Wag        manual   Vshaped
Datsun 710           manual  Straight
Hornet 4 Drive         auto  Straight
Hornet Sportabout      auto   Vshaped
Valiant                auto  Straight
Duster 360             auto   Vshaped
Merc 240D              auto  Straight
Merc 230               auto  Straight
Merc 280               auto  Straight
Merc 280C              auto  Straight
Merc 450SE             auto   Vshaped
Merc 450SL             auto   Vshaped
Merc 450SLC            auto   Vshaped
Cadillac Fleetwood     auto   Vshaped
Lincoln Continental    auto   Vshaped
Chrysler Imperial      auto   Vshaped
Fiat 128             manual  Straight
Honda Civic          manual  Straight
Toyota Corolla       manual  Straight
Toyota Corona          auto  Straight
Dodge Challenger       auto   Vshaped
AMC Javelin            auto   Vshaped
Camaro Z28             auto   Vshaped
Pontiac Firebird       auto   Vshaped
Fiat X1-9            manual  Straight
Porsche 914-2        manual   Vshaped
Lotus Europa         manual  Straight
Ford Pantera L       manual   Vshaped
Ferrari Dino         manual   Vshaped
Maserati Bora        manual   Vshaped
Volvo 142E           manual  Straight

In [46]:
mtcars[(mtcars['am'] == 'auto') &(mtcars['cyl']!='5') & (mtcars['mpg'] > 22)]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,Straight,auto,4,2,medium,low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.15,22.9,Straight,auto,4,2,medium,medium,Merc 230

In [47]:
mtcars.query("am == 'auto' and cyl != 5 and mpg >22") #same output we can write it down in both way

C:\Users\rajia\AppData\Local\Temp\ipykernel_15604\771190100.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  mtcars.query("am == 'auto' and cyl != 5 and mpg >22") #same output we can write it down in both way

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,Straight,auto,4,2,medium,low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.15,22.9,Straight,auto,4,2,medium,medium,Merc 230

In [48]:
mtcars[mtcars['mpg'].between(left= 23, right = 26.1, inclusive= 'left')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,Straight,auto,4,2,medium,low,Merc 240D
Porsche 914-2,26.0,4,120.3,91,4.43,2.14,16.7,Vshaped,manual,5,2,medium,medium,Porsche 914-2

In [49]:
mtcars[mtcars['mpg'].between(23,30, inclusive= 'neither')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.0,Straight,auto,4,2,medium,low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.9,Straight,manual,4,1,medium,low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,Vshaped,manual,5,2,medium,medium,Porsche 914-2

In [50]:
mtcars[mtcars['mpg'].between(23,30) & (mtcars['am']== 'manual')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.9,Straight,manual,4,1,medium,low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,Vshaped,manual,5,2,medium,medium,Porsche 914-2

In [51]:
mtcars[mtcars['gear'].isin([4,5])] # list cars whose gear is in values 4,5

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,medium,low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,medium,medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,medium,medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,medium,medium,Merc 280C
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,medium,medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,medium,medium,Volvo 142E

In [52]:
mtcars[mtcars['gear'].isin([4,5]) | (mtcars['am'] =='auto')]# all auto or gear = 4,5

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,medium,medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,medium,low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,medium,medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,medium,medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,medium,medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,medium,medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,low,medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,low,medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,medium,medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,medium,medium,Volvo 142E

In [53]:
mtcars[~mtcars['gear'].isin([4,5])]
# cars other gears values in 4,5 : ~ opposite

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,medium,medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,medium,medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,low,medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,low,medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird

# select dtypes

In [54]:
mtcars.dtypes

mpg           float64
cyl          category
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs           category
am           category
gear         category
carb         category
mpg_label    category
hp_label     category
car_name       object
dtype: object

In [55]:
mtcars.select_dtypes(include='number') # list columns which are numeric

                      mpg   disp   hp  drat     wt   qsec
Mazda RX4            21.0  160.0  110  3.90  2.620  16.46
Mazda RX4 Wag        21.0  160.0  110  3.90  2.875  17.02
Datsun 710           22.8  108.0   93  3.85  2.320  18.61
Hornet 4 Drive       21.4  258.0  110  3.08  3.215  19.44
Hornet Sportabout    18.7  360.0  175  3.15  3.440  17.02
Valiant              18.1  225.0  105  2.76  3.460  20.22
Duster 360           14.3  360.0  245  3.21  3.570  15.84
Merc 240D            24.4  146.7   62  3.69  3.190  20.00
Merc 230             22.8  140.8   95  3.92  3.150  22.90
Merc 280             19.2  167.6  123  3.92  3.440  18.30
Merc 280C            17.8  167.6  123  3.92  3.440  18.90
Merc 450SE           16.4  275.8  180  3.07  4.070  17.40
Merc 450SL           17.3  275.8  180  3.07  3.730  17.60
Merc 450SLC          15.2  275.8  180  3.07  3.780  18.00
Cadillac Fleetwood   10.4  472.0  205  2.93  5.250  17.98
Lincoln Continental  10.4  460.0  215  3.00  5.424  17.82
Chrysler Imperial    14.7  440.0  230  3.23  5.345  17.42
Fiat 128             32.4   78.7   66  4.08  2.200  19.47
Honda Civic          30.4   75.7   52  4.93  1.615  18.52
Toyota Corolla       33.9   71.1   65  4.22  1.835  19.90
Toyota Corona        21.5  120.1   97  3.70  2.465  20.01
Dodge Challenger     15.5  318.0  150  2.76  3.520  16.87
AMC Javelin          15.2  304.0  150  3.15  3.435  17.30
Camaro Z28           13.3  350.0  245  3.73  3.840  15.41
Pontiac Firebird     19.2  400.0  175  3.08  3.845  17.05
Fiat X1-9            27.3   79.0   66  4.08  1.935  18.90
Porsche 914-2        26.0  120.3   91  4.43  2.140  16.70
Lotus Europa         30.4   95.1  113  3.77  1.513  16.90
Ford Pantera L       15.8  351.0  264  4.22  3.170  14.50
Ferrari Dino         19.7  145.0  175  3.62  2.770  15.50
Maserati Bora        15.0  301.0  335  3.54  3.570  14.60
Volvo 142E           21.4  121.0  109  4.11  2.780  18.60

In [56]:
mtcars.select_dtypes(include='category').head()# list columns which category type

                  cyl        vs      am gear carb mpg_label hp_label
Mazda RX4           6   Vshaped  manual    4    4    medium   medium
Mazda RX4 Wag       6   Vshaped  manual    4    4    medium   medium
Datsun 710          4  Straight  manual    4    1    medium   medium
Hornet 4 Drive      6  Straight    auto    3    1    medium   medium
Hornet Sportabout   8   Vshaped    auto    3    2    medium     high

In [57]:
mtcars.select_dtypes(include='object').head()# string, car names

                            car_name
Mazda RX4                  Mazda RX4
Mazda RX4 Wag          Mazda RX4 Wag
Datsun 710                Datsun 710
Hornet 4 Drive        Hornet 4 Drive
Hornet Sportabout  Hornet Sportabout

# nlargest for a column

In [58]:
mtcars.nlargest(5,'mpg') # list cars which are among top 5 mpg

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9

In [59]:
mtcars.nsmallest(5,'wt')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,medium,medium,Porsche 914-2

# sort values

In [60]:
mtcars.sort_values(by ='mpg', ascending = True, inplace= True)
# list mtcars by mpg, in increasing order

In [61]:
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,low,medium,AMC Javelin
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,low,medium,Dodge Challenger
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,medium,medium,Merc 280C
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,medium,medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,medium,medium,Merc 280
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,medium,medium,Volvo 142E
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,medium,medium,Toyota Corona
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,medium,medium,Merc 230
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,medium,low,Merc 240D
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,medium,medium,Porsche 914-2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla

In [62]:
mtcars.sort_values(['gear','mpg'])#.head()  #first by gear, mpg

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,low,medium,AMC Javelin
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,low,medium,Dodge Challenger
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,medium,medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,medium,medium,Toyota Corona
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,medium,medium,Merc 280C
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,medium,medium,Merc 280
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,medium,medium,Volvo 142E
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,medium,medium,Merc 230
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,medium,low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,medium,medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa

In [63]:
mtcars.sort_values(['gear','mpg'], ascending= [False,True]) #.head()  #first by gear, mpg# gear:false:sorts gears from highest to lowest(decending)
#mpg:true: sorts mpg from lowest to highest(ascending)within each gear group.

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_label,hp_label,car_name
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,low,veryhigh,Maserati Bora
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,low,veryhigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,medium,high,Ferrari Dino
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,medium,medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,high,medium,Lotus Europa
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,medium,medium,Merc 280C
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,medium,medium,Merc 280
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,medium,medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,medium,medium,Mazda RX4 Wag
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,medium,medium,Volvo 142E
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,medium,medium,Merc 230
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,medium,medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,medium,low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,medium,low,Fiat X1-9
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,high,low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,high,low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,high,low,Toyota Corolla
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,low,high,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,low,high,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,low,high,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,low,high,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,low,high,Chrysler Imperial
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,low,high,Merc 450SLC
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,low,medium,AMC Javelin
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,low,medium,Dodge Challenger
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,low,high,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,medium,high,Merc 450SL
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,medium,medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,medium,high,Hornet Sportabout
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,medium,high,Pontiac Firebird
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,medium,medium,Hornet 4 Drive
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,medium,medium,Toyota Corona

# pivot class

In [64]:
import pandas as pd
import numpy  as np
from pydataset import data
mtcars= data('mtcars')
mtcars.shape

(32, 11)

In [65]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [66]:
mtcars.pivot_table(values='mpg',index='gear', observed = False)
# Mean mpg of Gear 3 cars is 16

            mpg
gear
3     16.106667
4     24.533333
5     21.380000

In [67]:
mtcars.pivot_table(values= 'hp',index='cyl',observed= False)# mean hp of Cyl-4 cars is 82

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [68]:
mtcars.pivot_table(values=['mpg','hp'],index=['gear','am'],observed= False,
                   aggfunc=['sum','mean','count']).reset_index()

  gear am   sum               mean            count
             hp    mpg          hp        mpg    hp mpg
0    3  0  2642  241.6  176.133333  16.106667    15  15
1    4  0   403   84.2  100.750000  21.050000     4   4
2    4  1   671  210.2   83.875000  26.275000     8   8
3    5  1   978  106.9  195.600000  21.380000     5   5

In [69]:
mtcars.pivot_table

<bound method DataFrame.pivot_table of                       mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4

                     carb
Mazda RX4               4
Mazda RX4 Wag           4
Datsun 710              1
Hornet 4 Drive          1
Hornet Sportabout       2
Valiant                 1
Duster 360              4
Merc 240D               2
Merc 230                2
Merc 280                4
Merc 280C               4
Merc 450SE              3
Merc 450SL              3
Merc 450SLC             3
Cadillac Fleetwood      4
Lincoln Continental     4
Chrysler Imperial       4
Fiat 128                1
Honda Civic             2
Toyota Corolla          1
Toyota Corona           1
Dodge Challenger        2
AMC Javelin             2
Camaro Z28              4
Pontiac Firebird        2
Fiat X1-9               1
Porsche 914-2           2
Lotus Europa            2
Ford Pantera L          4
Ferrari Dino            6
Maserati Bora           8
Volvo 142E              2  >

In [70]:
pd.pivot_table(data=mtcars, observed= False,
         index='gear',      #rows
         values='mpg',      #Values to summarize 
         aggfunc='median')    #Aggregation function
         # Median of Gear-3 cars is 15.5

       mpg
gear
3     15.5
4     22.8
5     19.7

In [76]:
pd.pivot_table= pd.pivot_table(
    data=mtcars, observed= False,
    index='gear',
    columns='am',
    values='mpg',
    aggfunc='mean'
)

TypeError: 'DataFrame' object is not callable