In [7]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd 
import os

In [8]:
engine1= create_engine("mysql+pymysql://root:piit2025@localhost:3306/piit")

In [9]:
def q(sql, **params):
 with engine1.connect() as conn:
  return pd.read_sql(text(sql), conn, params=params)

In [10]:
q ("select ename from emp where job in ('ANALYST','SALESMAN')")

      ename
0     ALLEN
1      WARD
2    MARTIN
3     SCOTT
4    TURNER
5      FORD
6  YOURNAME

In [12]:
q("select* from emp where hiredate >'1981-09-30'")

   empno     ename        job     mgr    hiredate     sal   comm  deptno
0   7788     SCOTT    ANALYST  7566.0  1982-12-09  3000.0    NaN      20
1   7839      KING  PRESIDENT     NaN  1981-11-17  5000.0    NaN      10
2   7876     ADAMS      CLERK  7788.0  1983-01-12  1100.0    NaN      20
3   7900     JAMES      CLERK  7698.0  1981-12-03   950.0    NaN      30
4   7902      FORD    ANALYST  7566.0  1981-12-03  3000.0    NaN      20
5   7934    MILLER      CLERK  7782.0  1982-01-23  1300.0    NaN      10
6   9999  YOURNAME    ANALYST  7839.0  2026-05-12  5000.0  100.0      10

In [14]:
q("select ename from emp where job != 'MANAGER'")

       ename
0      SMITH
1      ALLEN
2       WARD
3     MARTIN
4      SCOTT
5       KING
6     TURNER
7      ADAMS
8      JAMES
9       FORD
10    MILLER
11  YOURNAME

In [27]:
q("select ename from emp where empno in(7369,7521,7839,7934,7788)")

    ename
0   SMITH
1    WARD
2   SCOTT
3    KING
4  MILLER

In [34]:
q("select * from emp where deptno not in( 30, 40, 10)")

   empno  ename      job   mgr    hiredate     sal  comm  deptno
0   7369  SMITH    CLERK  7902  1980-12-17   800.0  None      20
1   7566  JONES  MANAGER  7839  1981-04-02  2975.0  None      20
2   7788  SCOTT  ANALYST  7566  1982-12-09  3000.0  None      20
3   7876  ADAMS    CLERK  7788  1983-01-12  1100.0  None      20
4   7902   FORD  ANALYST  7566  1981-12-03  3000.0  None      20

In [40]:
q("select ename from emp where hiredate between  '1981-06-30' and '1981-12-31'")

    ename
0  MARTIN
1    KING
2  TURNER
3   JAMES
4    FORD

In [42]:
q('select distinct job from emp')

         job
0      CLERK
1   SALESMAN
2    MANAGER
3    ANALYST
4  PRESIDENT

In [44]:
q('select ename from emp where comm is null or comm = 0')

     ename
0    SMITH
1    JONES
2    BLAKE
3    CLARK
4    SCOTT
5     KING
6   TURNER
7    ADAMS
8    JAMES
9     FORD
10  MILLER

In [45]:
q('select ename,job from emp where mgr is null')

  ename        job
0  KING  PRESIDENT

In [50]:
q('select * from emp where deptno is null')

Empty DataFrame
Columns: [empno, ename, job, mgr, hiredate, sal, comm, deptno]
Index: []

In [54]:
q('select ename from emp where comm is not null and comm > 0')

      ename
0     ALLEN
1      WARD
2    MARTIN
3  YOURNAME

In [57]:
q("select ename from emp where ename like '%s' or ename like 's%'")

   ename
0  SMITH
1  JONES
2  SCOTT
3  ADAMS
4  JAMES

In [59]:
q("select ename from emp where  ename like '_i%'")

    ename
0    KING
1  MILLER

In [65]:
q('select count(*) as total_employees from emp')

   total_employees
0               15

In [70]:
q('select count(distinct job) as unique_job from emp')

   unique_job
0           5

In [71]:
q('select sum(sal) as total_payroll from emp')

   total_payroll
0        34025.0

In [73]:
q('select max(sal) as max_sal, min(sal) as min_sal, avg(sal) as avg_sal from emp')

   max_sal  min_sal      avg_sal
0   5000.0    800.0  2268.333333

In [75]:
q("select max(sal) as max_sal from emp where job ='SALESMAN'")

   max_sal
0   1600.0