# Sql Python Connect

In [3]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [4]:
engine1 = create_engine("mysql+pymysql://root:piit2025@localhost:3306/piit")

In [5]:
# function to run the query with parameters or query
def q(sql, **params):
 with engine1.connect() as conn:
  return pd.read_sql(text(sql), conn, params=params)

In [6]:
q('show tables')

  Tables_in_piit
0         aelita
1           dept
2            emp
3       students

In [7]:
q ("select * from emp")

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
7    7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0     NaN      20
8    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0     NaN      20
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [8]:
emp=q("select * from emp")
emp.head()

   empno   ename       job     mgr    hiredate     sal    comm  deptno
0   7369   SMITH     CLERK  7902.0  1980-12-17   800.0     NaN      20
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
3   7566   JONES   MANAGER  7839.0  1981-04-02  2975.0     NaN      20
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30

In [9]:
emp.head()

   empno   ename       job     mgr    hiredate     sal    comm  deptno
0   7369   SMITH     CLERK  7902.0  1980-12-17   800.0     NaN      20
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
3   7566   JONES   MANAGER  7839.0  1981-04-02  2975.0     NaN      20
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30

In [10]:
q("select max(sal) from emp")

   max(sal)
0    5000.0

In [11]:
q("select avg(sal)  from emp")

      avg(sal)
0  2073.214286

In [12]:
query= 'select * from emp'
emp= pd.read_sql(query,engine1)
emp

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
7    7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0     NaN      20
8    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0     NaN      20
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [13]:
dept=q('select * from dept')
dept.head()

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [14]:
q('select max(deptno) from dept')

   max(deptno)
0         40.0

In [15]:
empdept= pd.merge(emp,dept,on='deptno',how='inner')
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO

In [16]:
empdept .groupby('dname').size()

dname
ACCOUNTING    3
RESEARCH      5
SALES         6
dtype: int64

In [17]:
empdept.groupby(['dname','job']).size().reset_index()

        dname        job  0
0  ACCOUNTING      CLERK  1
1  ACCOUNTING    MANAGER  1
2  ACCOUNTING  PRESIDENT  1
3    RESEARCH    ANALYST  2
4    RESEARCH      CLERK  2
5    RESEARCH    MANAGER  1
6       SALES      CLERK  1
7       SALES    MANAGER  1
8       SALES   SALESMAN  4

In [18]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO

#Query
Hiredates for emp of Research dept between 1990 to present
hiredate, dname

In [19]:
empdept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     14 non-null     int64
 1   ename     14 non-null     object
 2   job       14 non-null     object
 3   mgr       13 non-null     float64
 4   hiredate  14 non-null     object
 5   sal       14 non-null     float64
 6   comm      4 non-null      float64
 7   deptno    14 non-null     int64
 8   dname     14 non-null     object
 9   loc       14 non-null     object
dtypes: float64(3), int64(2), object(5)
memory usage: 1.2+ KB

In [20]:
import datetime as dt

In [21]:
empdept['hiredate'] = pd.to_datetime(empdept['hiredate'])

In [22]:
empdept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     14 non-null     int64
 1   ename     14 non-null     object
 2   job       14 non-null     object
 3   mgr       13 non-null     float64
 4   hiredate  14 non-null     datetime64[ns]
 5   sal       14 non-null     float64
 6   comm      4 non-null      float64
 7   deptno    14 non-null     int64
 8   dname     14 non-null     object
 9   loc       14 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 1.2+ KB

In [23]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO

In [24]:
empdept['hireyear']= empdept['hiredate'].dt.year
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS,1980
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS,1981
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO,1981

In [25]:
empdept[empdept['hireyear'] > 1980 ]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS,1981
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO,1981
5,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30,SALES,CHICAGO,1981
6,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10,ACCOUNTING,NEW YORK,1981
7,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS,1982
8,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,ACCOUNTING,NEW YORK,1981
9,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO,1981
10,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS,1983
11,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO,1981
12,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS,1981
13,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK,1982

In [26]:
empdept[(empdept['hireyear'] >= 1982) & (empdept['dname'] == 'RESEARCH')]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
7,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS,1982
10,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS,1983

In [27]:
empdept[(empdept['hiredate'].dt.year >= 1982) & (empdept['dname'] == 'RESEARCH')]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
7,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS,1982
10,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS,1983

In [28]:
today= pd.to_datetime('today')
today

Timestamp('2026-05-11 23:47:12.168251')

In [29]:
import numpy as np

In [30]:
empdept ['monthServed'] = ((today  - empdept['hiredate']) / np.timedelta64(1,'D')/ 30.44).astype(int)
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear,monthServed
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS,1980,544
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981,542
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981,542
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS,1981,541
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO,1981,535

In [31]:
empdept.drop(columns='monthServed', inplace=True)

In [32]:
empdept

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS,1980
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS,1981
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO,1981
5,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30,SALES,CHICAGO,1981
6,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10,ACCOUNTING,NEW YORK,1981
7,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS,1982
8,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,ACCOUNTING,NEW YORK,1981
9,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO,1981
10,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS,1983
11,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO,1981
12,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS,1981
13,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK,1982