Write the queries for the following
1.List the names of analysts and salesmen.
2.List details of employees who have joined before 30 Sep 81.
3.List names of employees who are not managers.
4.List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.
5.List employees not belonging to department 30, 40, or 10.
6.List employee names for those who have joined between 30 June and 31 Dec. ‘81.
7.List the different designations in the company.
8.List the names of employees who are not eligible for commission.
9.List the name and designation of the employee who does not report to anybody.
10.List the employees not assigned to any department.
11.List the employees who are eligible for commission.
12.List employees whose names either start or end with “S”.
13.List names of employees whose names have “i” as the second character.
14.List the number of employees working with the company.
15.List the number of designations available in the EMP table.
16.List the total salaries paid to the employees.
17.List the maximum, minimum and average salary in the company.
18.List the maximum salary paid to a salesman.

In [1]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd 
import os

In [2]:
engine1= create_engine("mysql+pymysql://root:piit2025@localhost:3306/piit")

In [3]:
def q(sql, **params):
 with engine1.connect() as conn:
  return pd.read_sql(text(sql), conn, params=params)

In [4]:
q("select ename from emp where job in ('ANALYST','SALESMAN')")

    ename
0  DHIRAJ
1    SHAN
2   ALLEN
3    WARD
4  MARTIN
5   SCOTT
6  TURNER
7    FORD

In [5]:
q("select* from emp where hiredate < '1981-09-30'")

   empno   ename       job   mgr    hiredate     sal    comm  deptno
0   7369   SMITH     CLERK  7902  1980-12-17   800.0     NaN      20
1   7499   ALLEN  SALESMAN  7698  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698  1981-02-22  1250.0   500.0      30
3   7566   JONES   MANAGER  7839  1981-04-02  2975.0     NaN      20
4   7654  MARTIN  SALESMAN  7698  1981-09-28  1250.0  1400.0      30
5   7698   BLAKE   MANAGER  7839  1981-05-01  2850.0     NaN      30
6   7782   CLARK   MANAGER  7839  1981-06-09  2450.0     NaN      10
7   7844  TURNER  SALESMAN  7698  1981-09-08  1500.0     0.0      30

In [6]:
q("select ename from emp where job != 'MANAGER'")

     ename
0   DHIRAJ
1     SHAN
2    SMITH
3    ALLEN
4     WARD
5   MARTIN
6    SCOTT
7     KING
8   TURNER
9    ADAMS
10   JAMES
11    FORD
12  MILLER

In [7]:
q("select ename from emp where empno IN (7369, 7521, 7839, 7934, 7788)")

    ename
0   SMITH
1    WARD
2   SCOTT
3    KING
4  MILLER

In [8]:
q("select * from emp WHERE deptno NOT IN (10, 30, 40)")

   empno  ename      job   mgr    hiredate     sal  comm  deptno
0   7369  SMITH    CLERK  7902  1980-12-17   800.0  None      20
1   7566  JONES  MANAGER  7839  1981-04-02  2975.0  None      20
2   7788  SCOTT  ANALYST  7566  1982-12-09  3000.0  None      20
3   7876  ADAMS    CLERK  7788  1983-01-12  1100.0  None      20
4   7902   FORD  ANALYST  7566  1981-12-03  3000.0  None      20

In [9]:
q("select ename from emp where hiredate between '1981-06-30' and '1981-12-31'")

    ename
0  MARTIN
1    KING
2  TURNER
3   JAMES
4    FORD

In [10]:
q("select distinct job from emp")

         job
0    ANALYST
1      CLERK
2   SALESMAN
3    MANAGER
4  PRESIDENT

In [11]:
q("select ename from emp where comm is null or comm = 0")

     ename
0    SMITH
1    JONES
2    BLAKE
3    CLARK
4    SCOTT
5     KING
6   TURNER
7    ADAMS
8    JAMES
9     FORD
10  MILLER

In [12]:
q('select ename, job from emp where mgr is null')

  ename        job
0  KING  PRESIDENT

In [13]:
q('select * from emp where deptno is null')

Empty DataFrame
Columns: [empno, ename, job, mgr, hiredate, sal, comm, deptno]
Index: []

In [14]:
q('select ename from emp where comm is not null and comm > 0')

    ename
0  DHIRAJ
1    SHAN
2   ALLEN
3    WARD
4  MARTIN

In [15]:
q("select ename from emp where ename like '%S' or ename like 'S%'")

   ename
0   SHAN
1  SMITH
2  JONES
3  SCOTT
4  ADAMS
5  JAMES

In [16]:
q("select ename from emp where ename like '_i%'")

    ename
0    KING
1  MILLER

In [17]:
q('select count(*) as total_employees from emp')

   total_employees
0               16

In [18]:
q("select count(distinct job) as unique_job from emp")

   unique_job
0           5

In [19]:
q('select sum(sal) as total_payroll from emp')

   total_payroll
0        38025.0

In [20]:
q('select max(sal) as max_sal,min(sal) as min_sal, avg(sal) as avg_sal from emp')

   max_sal  min_sal    avg_sal
0   5000.0    800.0  2376.5625

In [21]:
q("select max(sal) from emp where job= 'SALESMAN'")

   max(sal)
0    1600.0